#!/usr/bin/env rust-script

//! Complete test of unified component types with SVG generation
//! Run with: cargo run --bin test_unified_svg

use std::fs;
use anyhow::Result;
use log::info;

use bhdl_parser::parse;
use bhdl_ast::{SourceFile, AstNode};
use bhdl_analyzer::analyze;
use bhdl_synthesizer::{NetlistGenerator, NetlistConfig};
// Note: Visualizer has circular dependency, testing component mapping only

#[tokio::main]
async fn main() -> Result<()> {
    env_logger::init();
    
    println!("🧪 Testing Unified Component Types with SVG Generation");
    
    // Use the flow-based BHDL syntax
    let bhdl_source = r#"
board SimpleTest {
    VCC -> Res(4.7kΩ).1 -> LED(red).A;
    LED.K -> GND;
}
"#;

    println!("📄 Parsing BHDL with flow syntax...");
    let parse_result = parse(bhdl_source);
    let source_file = SourceFile::cast(parse_result.syntax()).unwrap();
    
    println!("🧠 Running semantic analysis...");
    let analysis = analyze(&source_file);
    
    println!("⚙️  Generating netlist with unified types...");
    let config = NetlistConfig {
        preserve_semantic_context: true,
        include_power_domains: true,
        include_component_inference: true,
        flatten_hierarchy: false,
        use_database_components: true,
        database_path: Some("/Users/girivs/src/bhdl-new/components.db".to_string()),
    };
    
    let mut generator = NetlistGenerator::with_config(config);
    let netlist = generator.generate_from_analysis(&analysis).await?;
    let components = generator.get_component_instances();
    
    println!("🔧 Component mapping results:");
    for comp in components {
        println!("  {} (BHDL: {}) -> {:?} (Refdes: {})", 
                 comp.component_name, comp.bhdl_type, 
                 comp.category, comp.instance_name);
    }
    
    println!("\n📊 Unified Component Type Test Results:");
    println!("  Total components: {}", components.len());
    
    // Test the unified type mapping
    for comp in components {
        let expected_refdes = match comp.bhdl_type.as_str() {
            "Res" => "R",
            "LED" => "LED", 
            _ => "U"
        };
        
        let actual_prefix = comp.instance_name.chars()
            .take_while(|c| c.is_alphabetic())
            .collect::<String>();
            
        let matches = actual_prefix == expected_refdes;
        let status = if matches { "✅" } else { "❌" };
        
        println!("  {} {} -> {} (Expected: {}*, Got: {})", 
                 status, comp.bhdl_type, comp.instance_name, expected_refdes, actual_prefix);
    }
    
    println!("\n🎯 Expected behavior:");
    println!("  - BHDL 'Res' type should generate 'R1', 'R2', etc.");
    println!("  - BHDL 'LED' type should generate 'LED1', 'LED2', etc.");
    println!("  - Visualizer should use these same reference designators");
    println!("\n💡 The SVG will be generated by the visualizer using these components.");
    println!("   Run the visualizer separately to see the corrected labels.");
    
    Ok(())
}