//! DIRECT FABRICATION OUTPUT — RS-274X Gerber + Excellon drill.
//!
//! The endgame of the KiCad-as-oracle doctrine: fab data written
//! straight from the placed-and-routed `Board`, with no EDA tool in
//! the path. KiCad stays the TEST oracle (its DRC judges our boards);
//! it stops being a required stage of the pipeline.
//!
//! Covers tracks, pads, via pads, mounting-hole annuli, the board
//! outline, the drill file, zone/pour copper, solder mask, solder
//! paste, silkscreen, and the .gbrjob that names them all.
//!
//! The zone copper is NOT recomputed here. It arrives as `BoardFills`
//! from the one place that computes it — the emission fixpoint, whose
//! passes are inseparable from the starved-pad accounting they feed.
//! Three arcs of this project were lost to mirrors of that
//! computation drifting from it; the cure is one computation with two
//! consumers, not a better mirror. A board therefore ships the exact
//! polygons its .kicad_pcb carries, bit for bit.
//!
//! Format: RS-274X, absolute, metric, 4.6 (nanometre resolution).
//! Rotated rectangular pads are emitted as REGIONS rather than
//! rotated apertures — the aperture primitives cannot express
//! rotation, and a region is exact where an axis-aligned
//! approximation would silently resize copper.

use crate::types::*;
use std::collections::BTreeMap;
use std::fmt::Write as _;

/// One Gerber file plus the name a fab house expects to see.
pub struct GerberFile {
    pub filename: String,
    pub contents: String,
}

/// Complete fabrication package for a board.
pub struct FabPackage {
    pub gerbers: Vec<GerberFile>,
    pub drill: GerberFile,
    pub manifest: String,
}

fn coord(v: f64) -> String {
    // 4.6 format: value in nanometres, no decimal point.
    format!("{}", (v * 1_000_000.0).round() as i64)
}

/// Y AXIS: the board model puts Y DOWN (same convention as the
/// .kicad_pcb this pipeline also writes); Gerber and Excellon put Y
/// UP. Every emitted Y must be negated or the fabricated board is
/// MIRRORED — caught by diffing bounding boxes against the oracle's
/// own export, which places the board at y in [-height, 0].
fn cy(v: f64) -> f64 {
    -v
}

fn header(layer_name: &str) -> String {
    let mut s = String::new();
    s.push_str("%FSLAX46Y46*%\n");
    s.push_str("%MOMM*%\n");
    s.push_str(&format!("G04 Layer {layer_name} generated by bhdl*\n"));
    s.push_str("%LPD*%\n");
    s.push_str("G01*\n");
    s
}

/// Aperture table: dedupe by rounded definition so a board with one
/// track width emits one aperture, not thousands.
#[derive(Default)]
struct Apertures {
    /// definition -> D-code
    map: BTreeMap<String, u32>,
    next: u32,
}

impl Apertures {
    fn new() -> Self {
        Apertures { map: BTreeMap::new(), next: 10 }
    }
    fn circle(&mut self, d: f64) -> u32 {
        self.get(format!("C,{:.6}", d))
    }
    fn rect(&mut self, w: f64, h: f64) -> u32 {
        self.get(format!("R,{:.6}X{:.6}", w, h))
    }
    fn obround(&mut self, w: f64, h: f64) -> u32 {
        self.get(format!("O,{:.6}X{:.6}", w, h))
    }
    fn get(&mut self, def: String) -> u32 {
        if let Some(&d) = self.map.get(&def) {
            return d;
        }
        let d = self.next;
        self.next += 1;
        self.map.insert(def, d);
        d
    }
    fn emit(&self) -> String {
        // D-code order, so the file reads deterministically.
        let mut by_code: Vec<(&u32, &String)> =
            self.map.iter().map(|(def, code)| (code, def)).collect();
        by_code.sort();
        let mut s = String::new();
        for (code, def) in by_code {
            let _ = writeln!(s, "%ADD{code}{def}*%");
        }
        s
    }
}

/// Pad outline in BOARD coordinates, rotation applied. Rect and
/// RoundRect give four corners (the rounding is a sub-0.1mm cosmetic
/// the fab's own tooling reproduces); Circle and Oval are flashed
/// with apertures instead and return None.
fn rotated_rect_corners(
    cx: f64,
    cy: f64,
    w: f64,
    h: f64,
    theta: f64,
) -> Vec<(f64, f64)> {
    let (co, sn) = (theta.cos(), theta.sin());
    let (hw, hh) = (w / 2.0, h / 2.0);
    [(-hw, -hh), (hw, -hh), (hw, hh), (-hw, hh)]
        .iter()
        .map(|&(dx, dy)| (cx + dx * co - dy * sn, cy + dx * sn + dy * co))
        .collect()
}

fn region(pts: &[(f64, f64)]) -> String {
    let mut s = String::new();
    s.push_str("G36*\n");
    for (i, (x, y)) in pts.iter().enumerate() {
        let op = if i == 0 { "D02" } else { "D01" };
        let _ = writeln!(s, "X{}Y{}{}*", coord(*x), coord(cy(*y)), op);
    }
    let _ = writeln!(s, "X{}Y{}D01*", coord(pts[0].0), coord(cy(pts[0].1)));
    s.push_str("G37*\n");
    s
}

/// Is this component's pad present on the given copper layer?
fn pad_on_layer(pad: &PadGeom, side: BoardSide, layer: usize, last: usize) -> bool {
    if pad.drill_mm.is_some() {
        return true; // through-hole: every copper layer
    }
    match side {
        BoardSide::Top => layer == 0,
        BoardSide::Bottom => layer == last,
    }
}

/// One copper layer as a Gerber file.
fn copper_layer(
    board: &Board,
    routes: &[Route],
    fills: &crate::output::kicad::BoardFills,
    layer: usize,
    name: &str,
) -> GerberFile {
    let last = board.layer_stack.layers.len().saturating_sub(1);
    let via_r = board.layer_stack.via.pad_mm / 2.0;
    let mut ap = Apertures::new();
    let mut body = String::new();

    // Tracks: a draw with a round aperture of the track's width.
    // Grouped by width so the aperture switches once per width.
    let mut by_width: BTreeMap<String, Vec<&RouteSegment>> = BTreeMap::new();
    for r in routes {
        for sg in &r.segments {
            if sg.layer != layer {
                continue;
            }
            by_width
                .entry(format!("{:.6}", sg.width_mm))
                .or_default()
                .push(sg);
        }
    }
    for (w_key, segs) in &by_width {
        let w: f64 = w_key.parse().unwrap_or(0.2);
        let d = ap.circle(w);
        let _ = writeln!(body, "D{d}*");
        for sg in segs {
            let _ = writeln!(
                body,
                "X{}Y{}D02*\nX{}Y{}D01*",
                coord(sg.start.0),
                coord(cy(sg.start.1)),
                coord(sg.end.0),
                coord(cy(sg.end.1))
            );
        }
    }

    // Via pads: one flash each.
    let vd = ap.circle(via_r * 2.0);
    let mut via_body = String::new();
    let mut any_via = false;
    for r in routes {
        for v in &r.vias {
            if !any_via {
                let _ = writeln!(via_body, "D{vd}*");
                any_via = true;
            }
            let _ = writeln!(via_body, "X{}Y{}D03*", coord(v.x), coord(cy(v.y)));
        }
    }
    body.push_str(&via_body);

    // Component pads.
    let mut pad_body = String::new();
    for comp in &board.components {
        let (co, sn) = (comp.theta.cos(), comp.theta.sin());
        for pin in &comp.pins {
            if pin.unplaced {
                continue;
            }
            let Some(pad) = &pin.pad else { continue };
            if !pad_on_layer(pad, comp.side, layer, last) {
                continue;
            }
            let gx = comp.x + pin.dx * co - pin.dy * sn;
            let gy = comp.y + pin.dx * sn + pin.dy * co;
            match pad.shape {
                PadShapeKind::Circle => {
                    let d = ap.circle(pad.width_mm.max(pad.height_mm));
                    let _ = writeln!(
                        pad_body,
                        "D{d}*\nX{}Y{}D03*",
                        coord(gx),
                        coord(cy(gy))
                    );
                }
                PadShapeKind::Oval => {
                    // Obround apertures are axis-aligned only. At a
                    // right-angle rotation the axes simply swap; at any
                    // other angle fall back to a region so copper is
                    // never silently resized.
                    let q = ((comp.theta / std::f64::consts::FRAC_PI_2).round()
                        * std::f64::consts::FRAC_PI_2
                        - comp.theta)
                        .abs();
                    if q < 1e-6 {
                        let quarter = ((comp.theta / std::f64::consts::FRAC_PI_2)
                            .round() as i64)
                            .rem_euclid(2);
                        let (w, h) = if quarter == 1 {
                            (pad.height_mm, pad.width_mm)
                        } else {
                            (pad.width_mm, pad.height_mm)
                        };
                        let d = ap.obround(w, h);
                        let _ = writeln!(
                            pad_body,
                            "D{d}*\nX{}Y{}D03*",
                            coord(gx),
                            coord(cy(gy))
                        );
                    } else {
                        let pts = rotated_rect_corners(
                            gx,
                            gy,
                            pad.width_mm,
                            pad.height_mm,
                            comp.theta,
                        );
                        pad_body.push_str(&region(&pts));
                    }
                }
                PadShapeKind::Rect | PadShapeKind::RoundRect => {
                    let q = ((comp.theta / std::f64::consts::FRAC_PI_2).round()
                        * std::f64::consts::FRAC_PI_2
                        - comp.theta)
                        .abs();
                    if q < 1e-6 {
                        let quarter = ((comp.theta / std::f64::consts::FRAC_PI_2)
                            .round() as i64)
                            .rem_euclid(2);
                        let (w, h) = if quarter == 1 {
                            (pad.height_mm, pad.width_mm)
                        } else {
                            (pad.width_mm, pad.height_mm)
                        };
                        let d = ap.rect(w, h);
                        let _ = writeln!(
                            pad_body,
                            "D{d}*\nX{}Y{}D03*",
                            coord(gx),
                            coord(cy(gy))
                        );
                    } else {
                        let pts = rotated_rect_corners(
                            gx,
                            gy,
                            pad.width_mm,
                            pad.height_mm,
                            comp.theta,
                        );
                        pad_body.push_str(&region(&pts));
                    }
                }
            }
        }
    }
    body.push_str(&pad_body);

    // Mounting-hole annuli: the KiCad writer gives each hole a pad of
    // drill + 0.5mm, and that copper is real on every layer.
    let mut mh_body = String::new();
    for hole in &board.config.mounting_holes {
        let d = ap.circle(hole.drill_mm + 0.5);
        let _ = writeln!(
            mh_body,
            "D{d}*\nX{}Y{}D03*",
            coord(hole.x_mm),
            coord(cy(hole.y_mm))
        );
    }
    body.push_str(&mh_body);

    // Zone/pour copper — the writer's own polygons, not a mirror of
    // them. Each fractured polygon (holes joined to the outline by
    // zero-width slits, exactly as KiCad stores them) becomes one
    // Gerber region.
    let mut zone_body = String::new();
    for zf in &fills.zones {
        if zf.layer != layer {
            continue;
        }
        for poly in &zf.polys {
            if poly.len() >= 3 {
                zone_body.push_str(&region(poly));
            }
        }
    }
    body.push_str(&zone_body);

    let mut s = header(name);
    s.push_str(&ap.emit());
    s.push_str(&body);
    s.push_str("M02*\n");
    GerberFile { filename: format!("{name}.gbr"), contents: s }
}

/// Board outline (Edge.Cuts).
fn edge_cuts(board: &Board) -> GerberFile {
    let mut ap = Apertures::new();
    let d = ap.circle(0.05);
    let pts: Vec<(f64, f64)> = match &board.config.outline {
        BoardOutline::Polygon(p) => p.clone(),
        _ => {
            let (w, h) = (board.config.outline.width(), board.config.outline.height());
            vec![(0.0, 0.0), (w, 0.0), (w, h), (0.0, h)]
        }
    };
    let mut body = String::new();
    let _ = writeln!(body, "D{d}*");
    if !pts.is_empty() {
        let _ = writeln!(body, "X{}Y{}D02*", coord(pts[0].0), coord(cy(pts[0].1)));
        for p in pts.iter().skip(1) {
            let _ = writeln!(body, "X{}Y{}D01*", coord(p.0), coord(cy(p.1)));
        }
        let _ = writeln!(body, "X{}Y{}D01*", coord(pts[0].0), coord(cy(pts[0].1)));
    }
    let mut s = header("Edge_Cuts");
    s.push_str(&ap.emit());
    s.push_str(&body);
    s.push_str("M02*\n");
    GerberFile { filename: "Edge_Cuts.gbr".into(), contents: s }
}

/// Excellon drill file: every via barrel and through-hole pad,
/// grouped into tools by diameter.
fn excellon(board: &Board, routes: &[Route]) -> GerberFile {
    let mut tools: BTreeMap<String, Vec<(f64, f64)>> = BTreeMap::new();
    let vd = format!("{:.3}", board.layer_stack.via.drill_mm);
    for r in routes {
        for v in &r.vias {
            tools.entry(vd.clone()).or_default().push((v.x, v.y));
        }
    }
    for comp in &board.components {
        let (co, sn) = (comp.theta.cos(), comp.theta.sin());
        for pin in &comp.pins {
            if pin.unplaced {
                continue;
            }
            let Some(pad) = &pin.pad else { continue };
            let Some(drill) = pad.drill_mm else { continue };
            tools.entry(format!("{:.3}", drill)).or_default().push((
                comp.x + pin.dx * co - pin.dy * sn,
                comp.y + pin.dx * sn + pin.dy * co,
            ));
        }
    }
    for hole in &board.config.mounting_holes {
        tools
            .entry(format!("{:.3}", hole.drill_mm))
            .or_default()
            .push((hole.x_mm, hole.y_mm));
    }

    let mut s = String::new();
    s.push_str("M48\n");
    s.push_str("; Excellon drill file generated by bhdl\n");
    s.push_str("FMAT,2\n");
    s.push_str("METRIC,TZ\n");
    let names: Vec<&String> = tools.keys().collect();
    for (i, dia) in names.iter().enumerate() {
        let _ = writeln!(s, "T{}C{}", i + 1, dia);
    }
    s.push_str("%\n");
    s.push_str("G90\n");
    s.push_str("G05\n");
    for (i, dia) in names.iter().enumerate() {
        let _ = writeln!(s, "T{}", i + 1);
        for (x, y) in &tools[*dia] {
            let _ = writeln!(s, "X{:.3}Y{:.3}", x, cy(*y));
        }
    }
    s.push_str("T0\n");
    s.push_str("M30\n");
    GerberFile { filename: "drill.drl".into(), contents: s }
}


/// SOLDER MASK — the openings, one per soldered pad.
///
/// Two rules taken from the oracle's own export rather than assumed:
/// VIAS ARE TENTED (covered — they are not soldered, and an open via
/// is a solder thief), and the opening is the pad shape expanded by
/// the board's mask margin. Component pads and mounting-hole annuli
/// open; via pads do not.
fn mask_layer(board: &Board, layer_top: bool, name: &str) -> GerberFile {
    let mut ap = Apertures::new();
    let mut body = String::new();
    // No board-level mask setting exists in the model yet; the
    // corpus's own footprints carry zero expansion (verified against
    // the oracle's export: mask apertures equal copper pads exactly),
    // so zero is the faithful default rather than an invented number.
    let exp = 0.0f64;
    for comp in &board.components {
        let on_side = if layer_top {
            comp.side == BoardSide::Top
        } else {
            comp.side == BoardSide::Bottom
        };
        let (co, sn) = (comp.theta.cos(), comp.theta.sin());
        for pin in &comp.pins {
            if pin.unplaced {
                continue;
            }
            let Some(pad) = &pin.pad else { continue };
            // Through-hole pads break both faces; SMD only its own.
            if pad.drill_mm.is_none() && !on_side {
                continue;
            }
            let gx = comp.x + pin.dx * co - pin.dy * sn;
            let gy = comp.y + pin.dx * sn + pin.dy * co;
            let (w, h) = (pad.width_mm + 2.0 * exp, pad.height_mm + 2.0 * exp);
            emit_pad(&mut ap, &mut body, pad.shape, gx, gy, w, h, comp.theta);
        }
    }
    for hole in &board.config.mounting_holes {
        let d = ap.circle(hole.drill_mm + 0.5 + 2.0 * exp);
        let _ = writeln!(
            body,
            "D{d}*\nX{}Y{}D03*",
            coord(hole.x_mm),
            coord(cy(hole.y_mm))
        );
    }
    let mut s = header(name);
    s.push_str(&ap.emit());
    s.push_str(&body);
    s.push_str("M02*\n");
    GerberFile { filename: format!("{name}.gbr"), contents: s }
}

/// SOLDER PASTE — stencil apertures, SMD pads only.
///
/// Through-hole joints are wave- or hand-soldered and must NOT get
/// paste; vias must not either. A board with no SMD parts therefore
/// yields an empty (but present) paste layer, which is exactly what
/// the oracle emits for the all-through-hole ecc83.
fn paste_layer(board: &Board, layer_top: bool, name: &str) -> GerberFile {
    let mut ap = Apertures::new();
    let mut body = String::new();
    // Likewise no paste margin in the model; 0 keeps the stencil
    // aperture equal to the pad, which is what the oracle emits here.
    let shrink = 0.0f64;
    for comp in &board.components {
        let on_side = if layer_top {
            comp.side == BoardSide::Top
        } else {
            comp.side == BoardSide::Bottom
        };
        if !on_side {
            continue;
        }
        let (co, sn) = (comp.theta.cos(), comp.theta.sin());
        for pin in &comp.pins {
            if pin.unplaced {
                continue;
            }
            let Some(pad) = &pin.pad else { continue };
            if pad.drill_mm.is_some() {
                continue; // through-hole: no paste
            }
            let gx = comp.x + pin.dx * co - pin.dy * sn;
            let gy = comp.y + pin.dx * sn + pin.dy * co;
            let (w, h) = (
                (pad.width_mm + 2.0 * shrink).max(0.05),
                (pad.height_mm + 2.0 * shrink).max(0.05),
            );
            emit_pad(&mut ap, &mut body, pad.shape, gx, gy, w, h, comp.theta);
        }
    }
    let mut s = header(name);
    s.push_str(&ap.emit());
    s.push_str(&body);
    s.push_str("M02*\n");
    GerberFile { filename: format!("{name}.gbr"), contents: s }
}

/// Flash or region a pad of the given shape — shared by copper, mask
/// and paste so the three layers can never disagree about a pad's
/// outline.
fn emit_pad(
    ap: &mut Apertures,
    body: &mut String,
    shape: PadShapeKind,
    gx: f64,
    gy: f64,
    w: f64,
    h: f64,
    theta: f64,
) {
    let axis_aligned = ((theta / std::f64::consts::FRAC_PI_2).round()
        * std::f64::consts::FRAC_PI_2
        - theta)
        .abs()
        < 1e-6;
    let quarter = ((theta / std::f64::consts::FRAC_PI_2).round() as i64).rem_euclid(2);
    let (aw, ah) = if quarter == 1 { (h, w) } else { (w, h) };
    match shape {
        PadShapeKind::Circle => {
            let d = ap.circle(w.max(h));
            let _ = writeln!(body, "D{d}*\nX{}Y{}D03*", coord(gx), coord(cy(gy)));
        }
        PadShapeKind::Oval if axis_aligned => {
            let d = ap.obround(aw, ah);
            let _ = writeln!(body, "D{d}*\nX{}Y{}D03*", coord(gx), coord(cy(gy)));
        }
        PadShapeKind::Rect | PadShapeKind::RoundRect if axis_aligned => {
            let d = ap.rect(aw, ah);
            let _ = writeln!(body, "D{d}*\nX{}Y{}D03*", coord(gx), coord(cy(gy)));
        }
        _ => {
            let pts = rotated_rect_corners(gx, gy, w, h, theta);
            body.push_str(&region(&pts));
        }
    }
}

/// Single-stroke glyphs on a 0..1 x 0..1 box, as polylines.
///
/// Silkscreen is legibility, not geometry: no oracle comparison
/// applies (KiCad draws its own font, and a fab house cares only that
/// the reference designators can be read during assembly). Uppercase,
/// digits and the few separators our refdes allocator emits.
fn glyph(c: char) -> &'static [&'static [(f64, f64)]] {
    match c {
        'A' => &[&[(0.0, 0.0), (0.5, 1.0), (1.0, 0.0)], &[(0.2, 0.4), (0.8, 0.4)]],
        'B' => &[&[(0.0, 0.0), (0.0, 1.0), (0.7, 1.0), (0.9, 0.8), (0.7, 0.5), (0.0, 0.5)], &[(0.7, 0.5), (0.95, 0.25), (0.7, 0.0), (0.0, 0.0)]],
        'C' => &[&[(1.0, 0.8), (0.7, 1.0), (0.3, 1.0), (0.0, 0.7), (0.0, 0.3), (0.3, 0.0), (0.7, 0.0), (1.0, 0.2)]],
        'D' => &[&[(0.0, 0.0), (0.0, 1.0), (0.6, 1.0), (1.0, 0.6), (1.0, 0.4), (0.6, 0.0), (0.0, 0.0)]],
        'E' => &[&[(1.0, 1.0), (0.0, 1.0), (0.0, 0.0), (1.0, 0.0)], &[(0.0, 0.5), (0.7, 0.5)]],
        'F' => &[&[(1.0, 1.0), (0.0, 1.0), (0.0, 0.0)], &[(0.0, 0.5), (0.7, 0.5)]],
        'G' => &[&[(1.0, 0.8), (0.7, 1.0), (0.3, 1.0), (0.0, 0.7), (0.0, 0.3), (0.3, 0.0), (0.8, 0.0), (1.0, 0.2), (1.0, 0.45), (0.55, 0.45)]],
        'H' => &[&[(0.0, 1.0), (0.0, 0.0)], &[(1.0, 1.0), (1.0, 0.0)], &[(0.0, 0.5), (1.0, 0.5)]],
        'I' => &[&[(0.5, 1.0), (0.5, 0.0)], &[(0.2, 1.0), (0.8, 1.0)], &[(0.2, 0.0), (0.8, 0.0)]],
        'J' => &[&[(0.8, 1.0), (0.8, 0.2), (0.5, 0.0), (0.2, 0.2)]],
        'K' => &[&[(0.0, 1.0), (0.0, 0.0)], &[(1.0, 1.0), (0.0, 0.45)], &[(0.3, 0.6), (1.0, 0.0)]],
        'L' => &[&[(0.0, 1.0), (0.0, 0.0), (1.0, 0.0)]],
        'M' => &[&[(0.0, 0.0), (0.0, 1.0), (0.5, 0.5), (1.0, 1.0), (1.0, 0.0)]],
        'N' => &[&[(0.0, 0.0), (0.0, 1.0), (1.0, 0.0), (1.0, 1.0)]],
        'O' => &[&[(0.3, 1.0), (0.7, 1.0), (1.0, 0.7), (1.0, 0.3), (0.7, 0.0), (0.3, 0.0), (0.0, 0.3), (0.0, 0.7), (0.3, 1.0)]],
        'P' => &[&[(0.0, 0.0), (0.0, 1.0), (0.7, 1.0), (1.0, 0.8), (0.7, 0.55), (0.0, 0.55)]],
        'Q' => &[&[(0.3, 1.0), (0.7, 1.0), (1.0, 0.7), (1.0, 0.3), (0.7, 0.0), (0.3, 0.0), (0.0, 0.3), (0.0, 0.7), (0.3, 1.0)], &[(0.6, 0.3), (1.0, -0.1)]],
        'R' => &[&[(0.0, 0.0), (0.0, 1.0), (0.7, 1.0), (1.0, 0.8), (0.7, 0.55), (0.0, 0.55)], &[(0.5, 0.55), (1.0, 0.0)]],
        'S' => &[&[(1.0, 0.85), (0.7, 1.0), (0.25, 1.0), (0.0, 0.8), (0.25, 0.55), (0.75, 0.5), (1.0, 0.25), (0.7, 0.0), (0.25, 0.0), (0.0, 0.15)]],
        'T' => &[&[(0.0, 1.0), (1.0, 1.0)], &[(0.5, 1.0), (0.5, 0.0)]],
        'U' => &[&[(0.0, 1.0), (0.0, 0.25), (0.3, 0.0), (0.7, 0.0), (1.0, 0.25), (1.0, 1.0)]],
        'V' => &[&[(0.0, 1.0), (0.5, 0.0), (1.0, 1.0)]],
        'W' => &[&[(0.0, 1.0), (0.25, 0.0), (0.5, 0.6), (0.75, 0.0), (1.0, 1.0)]],
        'X' => &[&[(0.0, 1.0), (1.0, 0.0)], &[(0.0, 0.0), (1.0, 1.0)]],
        'Y' => &[&[(0.0, 1.0), (0.5, 0.5), (1.0, 1.0)], &[(0.5, 0.5), (0.5, 0.0)]],
        'Z' => &[&[(0.0, 1.0), (1.0, 1.0), (0.0, 0.0), (1.0, 0.0)]],
        '0' => &[&[(0.3, 1.0), (0.7, 1.0), (1.0, 0.7), (1.0, 0.3), (0.7, 0.0), (0.3, 0.0), (0.0, 0.3), (0.0, 0.7), (0.3, 1.0)], &[(0.0, 0.0), (1.0, 1.0)]],
        '1' => &[&[(0.25, 0.8), (0.5, 1.0), (0.5, 0.0)], &[(0.2, 0.0), (0.8, 0.0)]],
        '2' => &[&[(0.0, 0.8), (0.25, 1.0), (0.75, 1.0), (1.0, 0.75), (0.0, 0.0), (1.0, 0.0)]],
        '3' => &[&[(0.0, 1.0), (1.0, 1.0), (0.45, 0.55)], &[(0.45, 0.55), (1.0, 0.3), (0.7, 0.0), (0.2, 0.0), (0.0, 0.15)]],
        '4' => &[&[(0.75, 0.0), (0.75, 1.0), (0.0, 0.3), (1.0, 0.3)]],
        '5' => &[&[(1.0, 1.0), (0.0, 1.0), (0.0, 0.55), (0.7, 0.55), (1.0, 0.3), (0.7, 0.0), (0.2, 0.0), (0.0, 0.15)]],
        '6' => &[&[(0.9, 0.9), (0.6, 1.0), (0.2, 0.85), (0.0, 0.4), (0.2, 0.05), (0.6, 0.0), (0.9, 0.2), (0.85, 0.45), (0.5, 0.6), (0.15, 0.5)]],
        '7' => &[&[(0.0, 1.0), (1.0, 1.0), (0.4, 0.0)]],
        '8' => &[&[(0.3, 0.55), (0.0, 0.75), (0.2, 1.0), (0.8, 1.0), (1.0, 0.75), (0.7, 0.55), (0.3, 0.55)], &[(0.7, 0.55), (1.0, 0.3), (0.75, 0.0), (0.25, 0.0), (0.0, 0.3), (0.3, 0.55)]],
        '9' => &[&[(0.1, 0.1), (0.4, 0.0), (0.8, 0.15), (1.0, 0.6), (0.8, 0.95), (0.4, 1.0), (0.1, 0.8), (0.15, 0.55), (0.5, 0.4), (0.85, 0.5)]],
        '_' => &[&[(0.0, 0.0), (1.0, 0.0)]],
        '-' => &[&[(0.15, 0.5), (0.85, 0.5)]],
        '.' => &[&[(0.45, 0.0), (0.55, 0.0)]],
        '+' => &[&[(0.5, 0.85), (0.5, 0.15)], &[(0.15, 0.5), (0.85, 0.5)]],
        _ => &[],
    }
}

/// SILKSCREEN — reference designators, so a human can populate the
/// board. Placed above each footprint, centred, in a single-stroke
/// font. Cosmetic by nature: the bar is legibility and correct
/// placement, not agreement with any other tool's glyph shapes.
fn silk_layer(board: &Board, layer_top: bool, name: &str) -> GerberFile {
    let mut ap = Apertures::new();
    let stroke = 0.15f64;
    let d = ap.circle(stroke);
    let mut body = String::new();
    let _ = writeln!(body, "D{d}*");
    let size = 0.9f64; // cap height
    for comp in &board.components {
        let on_side = if layer_top {
            comp.side == BoardSide::Top
        } else {
            comp.side == BoardSide::Bottom
        };
        if !on_side || comp.refdes.is_empty() {
            continue;
        }
        let text: String = comp.refdes.to_uppercase();
        let adv = size * 0.75;
        let total = adv * text.chars().count() as f64;
        // Above the part, clear of its own body.
        let bx = comp.x - total / 2.0;
        let by = comp.y - (comp.height_mm / 2.0 + 0.35 + size);
        for (i, ch) in text.chars().enumerate() {
            let ox = bx + i as f64 * adv;
            for stroke_pts in glyph(ch) {
                if stroke_pts.len() < 2 {
                    continue;
                }
                for (k, (px, py)) in stroke_pts.iter().enumerate() {
                    let x = ox + px * size * 0.62;
                    // Glyph Y is up; board Y is down.
                    let y = by + (1.0 - py) * size;
                    let op = if k == 0 { "D02" } else { "D01" };
                    let _ = writeln!(body, "X{}Y{}{}*", coord(x), coord(cy(y)), op);
                }
            }
        }
    }
    let mut s = header(name);
    s.push_str(&ap.emit());
    s.push_str(&body);
    s.push_str("M02*\n");
    GerberFile { filename: format!("{name}.gbr"), contents: s }
}

/// Gerber job file (.gbrjob): the machine-readable index a fab house
/// loads to know which file is which layer, so nobody guesses from
/// extensions.
fn job_file(board: &Board, gerbers: &[GerberFile], drill: &GerberFile) -> GerberFile {
    let n_cu = board
        .layer_stack
        .layers
        .iter()
        .filter(|l| l.kind == LayerKind::Signal)
        .count();
    let mut files = String::new();
    for (i, g) in gerbers.iter().enumerate() {
        let stem = g.filename.trim_end_matches(".gbr");
        let function = match stem {
            "F_Cu" => "\"Copper,L1,Top\"".to_string(),
            "B_Cu" => format!("\"Copper,L{n_cu},Bot\""),
            "Edge_Cuts" => "\"Profile,NP\"".to_string(),
            "F_Mask" => "\"SolderMask,Top\"".to_string(),
            "B_Mask" => "\"SolderMask,Bot\"".to_string(),
            "F_Paste" => "\"SolderPaste,Top\"".to_string(),
            "B_Paste" => "\"SolderPaste,Bot\"".to_string(),
            "F_Silkscreen" => "\"Legend,Top\"".to_string(),
            "B_Silkscreen" => "\"Legend,Bot\"".to_string(),
            _ => "\"Other\"".to_string(),
        };
        let comma = if i + 1 < gerbers.len() { "," } else { "" };
        let _ = writeln!(
            files,
            "      {{ \"Path\": \"{}\", \"FileFunction\": {} }}{}",
            g.filename, function, comma
        );
    }
    let contents = format!(
        r#"{{
  "Header": {{
    "GenerationSoftware": {{ "Vendor": "bhdl", "Application": "bhdl-cli" }},
    "CreationDate": "generated"
  }},
  "GeneralSpecs": {{
    "ProjectId": {{ "Name": "{name}" }},
    "Size": {{ "X": {w:.3}, "Y": {h:.3} }},
    "LayerNumber": {n_cu},
    "BoardThickness": {thick:.3}
  }},
  "FilesAttributes": [
{files}  ],
  "DrillFiles": [ {{ "Path": "{drill}" }} ]
}}
"#,
        name = "board",
        w = board.config.outline.width(),
        h = board.config.outline.height(),
        n_cu = n_cu,
        thick = board.layer_stack.total_thickness_mm,
        files = files,
        drill = drill.filename,
    );
    GerberFile { filename: "board.gbrjob".into(), contents }
}

/// Build the full package for a placed-and-routed board.
pub fn export_fab(
    board: &Board,
    routes: &[Route],
    fills: &crate::output::kicad::BoardFills,
) -> FabPackage {
    let mut gerbers = Vec::new();
    for (i, layer) in board.layer_stack.layers.iter().enumerate() {
        if layer.kind != LayerKind::Signal {
            continue;
        }
        let name = layer.name.replace('.', "_");
        gerbers.push(copper_layer(board, routes, fills, i, &name));
    }
    let two_sided = board.layer_stack.layers.len() >= 2;
    gerbers.push(mask_layer(board, true, "F_Mask"));
    if two_sided {
        gerbers.push(mask_layer(board, false, "B_Mask"));
    }
    gerbers.push(paste_layer(board, true, "F_Paste"));
    if two_sided {
        gerbers.push(paste_layer(board, false, "B_Paste"));
    }
    gerbers.push(silk_layer(board, true, "F_Silkscreen"));
    if two_sided {
        gerbers.push(silk_layer(board, false, "B_Silkscreen"));
    }
    gerbers.push(edge_cuts(board));
    let drill = excellon(board, routes);
    let job = job_file(board, &gerbers, &drill);
    gerbers.push(job);

    let n_tracks: usize = routes.iter().map(|r| r.segments.len()).sum();
    let n_vias: usize = routes.iter().map(|r| r.vias.len()).sum();
    let poured: Vec<&str> = board
        .nets
        .iter()
        .filter(|n| n.plane_layer.is_some())
        .map(|n| n.name.as_str())
        .collect();
    let mut manifest = String::new();
    manifest.push_str("bhdl fabrication package\n");
    manifest.push_str("========================\n\n");
    let _ = writeln!(manifest, "tracks: {n_tracks}\nvias:   {n_vias}");
    let _ = writeln!(
        manifest,
        "board:  {:.2} x {:.2} mm",
        board.config.outline.width(),
        board.config.outline.height()
    );
    manifest.push_str("\nFiles:\n");
    for g in &gerbers {
        let _ = writeln!(manifest, "  {}", g.filename);
    }
    let _ = writeln!(manifest, "  {}", drill.filename);
    let n_zone_polys: usize = fills.zones.iter().map(|z| z.polys.len()).sum();
    let _ = writeln!(manifest, "zones:  {n_zone_polys} filled polygon(s)");
    if !poured.is_empty() {
        manifest.push_str("\nPoured nets (zone copper included):\n");
        for p in &poured {
            let _ = writeln!(manifest, "  - {p}");
        }
    }
    FabPackage { gerbers, drill, manifest }
}
