//! DIRECT FABRICATION OUTPUT — RS-274X Gerber + Excellon drill.
//!
//! The endgame of the KiCad-as-oracle doctrine: fab data written
//! straight from the placed-and-routed `Board`, with no EDA tool in
//! the path. KiCad stays the TEST oracle (its DRC judges our boards);
//! it stops being a required stage of the pipeline.
//!
//! Covers tracks, pads, via pads, mounting-hole annuli, the board
//! outline, the drill file, AND zone/pour copper.
//!
//! The zone copper is NOT recomputed here. It arrives as `BoardFills`
//! from the one place that computes it — the emission fixpoint, whose
//! passes are inseparable from the starved-pad accounting they feed.
//! Three arcs of this project were lost to mirrors of that
//! computation drifting from it; the cure is one computation with two
//! consumers, not a better mirror. A board therefore ships the exact
//! polygons its .kicad_pcb carries, bit for bit.
//!
//! Format: RS-274X, absolute, metric, 4.6 (nanometre resolution).
//! Rotated rectangular pads are emitted as REGIONS rather than
//! rotated apertures — the aperture primitives cannot express
//! rotation, and a region is exact where an axis-aligned
//! approximation would silently resize copper.

use crate::types::*;
use std::collections::BTreeMap;
use std::fmt::Write as _;

/// One Gerber file plus the name a fab house expects to see.
pub struct GerberFile {
    pub filename: String,
    pub contents: String,
}

/// Complete fabrication package for a board.
pub struct FabPackage {
    pub gerbers: Vec<GerberFile>,
    pub drill: GerberFile,
    pub manifest: String,
}

fn coord(v: f64) -> String {
    // 4.6 format: value in nanometres, no decimal point.
    format!("{}", (v * 1_000_000.0).round() as i64)
}

/// Y AXIS: the board model puts Y DOWN (same convention as the
/// .kicad_pcb this pipeline also writes); Gerber and Excellon put Y
/// UP. Every emitted Y must be negated or the fabricated board is
/// MIRRORED — caught by diffing bounding boxes against the oracle's
/// own export, which places the board at y in [-height, 0].
fn cy(v: f64) -> f64 {
    -v
}

fn header(layer_name: &str) -> String {
    let mut s = String::new();
    s.push_str("%FSLAX46Y46*%\n");
    s.push_str("%MOMM*%\n");
    s.push_str(&format!("G04 Layer {layer_name} generated by bhdl*\n"));
    s.push_str("%LPD*%\n");
    s.push_str("G01*\n");
    s
}

/// Aperture table: dedupe by rounded definition so a board with one
/// track width emits one aperture, not thousands.
#[derive(Default)]
struct Apertures {
    /// definition -> D-code
    map: BTreeMap<String, u32>,
    next: u32,
}

impl Apertures {
    fn new() -> Self {
        Apertures { map: BTreeMap::new(), next: 10 }
    }
    fn circle(&mut self, d: f64) -> u32 {
        self.get(format!("C,{:.6}", d))
    }
    fn rect(&mut self, w: f64, h: f64) -> u32 {
        self.get(format!("R,{:.6}X{:.6}", w, h))
    }
    fn obround(&mut self, w: f64, h: f64) -> u32 {
        self.get(format!("O,{:.6}X{:.6}", w, h))
    }
    fn get(&mut self, def: String) -> u32 {
        if let Some(&d) = self.map.get(&def) {
            return d;
        }
        let d = self.next;
        self.next += 1;
        self.map.insert(def, d);
        d
    }
    fn emit(&self) -> String {
        // D-code order, so the file reads deterministically.
        let mut by_code: Vec<(&u32, &String)> =
            self.map.iter().map(|(def, code)| (code, def)).collect();
        by_code.sort();
        let mut s = String::new();
        for (code, def) in by_code {
            let _ = writeln!(s, "%ADD{code}{def}*%");
        }
        s
    }
}

/// Pad outline in BOARD coordinates, rotation applied. Rect and
/// RoundRect give four corners (the rounding is a sub-0.1mm cosmetic
/// the fab's own tooling reproduces); Circle and Oval are flashed
/// with apertures instead and return None.
fn rotated_rect_corners(
    cx: f64,
    cy: f64,
    w: f64,
    h: f64,
    theta: f64,
) -> Vec<(f64, f64)> {
    let (co, sn) = (theta.cos(), theta.sin());
    let (hw, hh) = (w / 2.0, h / 2.0);
    [(-hw, -hh), (hw, -hh), (hw, hh), (-hw, hh)]
        .iter()
        .map(|&(dx, dy)| (cx + dx * co - dy * sn, cy + dx * sn + dy * co))
        .collect()
}

fn region(pts: &[(f64, f64)]) -> String {
    let mut s = String::new();
    s.push_str("G36*\n");
    for (i, (x, y)) in pts.iter().enumerate() {
        let op = if i == 0 { "D02" } else { "D01" };
        let _ = writeln!(s, "X{}Y{}{}*", coord(*x), coord(cy(*y)), op);
    }
    let _ = writeln!(s, "X{}Y{}D01*", coord(pts[0].0), coord(cy(pts[0].1)));
    s.push_str("G37*\n");
    s
}

/// Is this component's pad present on the given copper layer?
fn pad_on_layer(pad: &PadGeom, side: BoardSide, layer: usize, last: usize) -> bool {
    if pad.drill_mm.is_some() {
        return true; // through-hole: every copper layer
    }
    match side {
        BoardSide::Top => layer == 0,
        BoardSide::Bottom => layer == last,
    }
}

/// One copper layer as a Gerber file.
fn copper_layer(
    board: &Board,
    routes: &[Route],
    fills: &crate::output::kicad::BoardFills,
    layer: usize,
    name: &str,
) -> GerberFile {
    let last = board.layer_stack.layers.len().saturating_sub(1);
    let via_r = board.layer_stack.via.pad_mm / 2.0;
    let mut ap = Apertures::new();
    let mut body = String::new();

    // Tracks: a draw with a round aperture of the track's width.
    // Grouped by width so the aperture switches once per width.
    let mut by_width: BTreeMap<String, Vec<&RouteSegment>> = BTreeMap::new();
    for r in routes {
        for sg in &r.segments {
            if sg.layer != layer {
                continue;
            }
            by_width
                .entry(format!("{:.6}", sg.width_mm))
                .or_default()
                .push(sg);
        }
    }
    for (w_key, segs) in &by_width {
        let w: f64 = w_key.parse().unwrap_or(0.2);
        let d = ap.circle(w);
        let _ = writeln!(body, "D{d}*");
        for sg in segs {
            let _ = writeln!(
                body,
                "X{}Y{}D02*\nX{}Y{}D01*",
                coord(sg.start.0),
                coord(cy(sg.start.1)),
                coord(sg.end.0),
                coord(cy(sg.end.1))
            );
        }
    }

    // Via pads: one flash each.
    let vd = ap.circle(via_r * 2.0);
    let mut via_body = String::new();
    let mut any_via = false;
    for r in routes {
        for v in &r.vias {
            if !any_via {
                let _ = writeln!(via_body, "D{vd}*");
                any_via = true;
            }
            let _ = writeln!(via_body, "X{}Y{}D03*", coord(v.x), coord(cy(v.y)));
        }
    }
    body.push_str(&via_body);

    // Component pads.
    let mut pad_body = String::new();
    for comp in &board.components {
        let (co, sn) = (comp.theta.cos(), comp.theta.sin());
        for pin in &comp.pins {
            if pin.unplaced {
                continue;
            }
            let Some(pad) = &pin.pad else { continue };
            if !pad_on_layer(pad, comp.side, layer, last) {
                continue;
            }
            let gx = comp.x + pin.dx * co - pin.dy * sn;
            let gy = comp.y + pin.dx * sn + pin.dy * co;
            match pad.shape {
                PadShapeKind::Circle => {
                    let d = ap.circle(pad.width_mm.max(pad.height_mm));
                    let _ = writeln!(
                        pad_body,
                        "D{d}*\nX{}Y{}D03*",
                        coord(gx),
                        coord(cy(gy))
                    );
                }
                PadShapeKind::Oval => {
                    // Obround apertures are axis-aligned only. At a
                    // right-angle rotation the axes simply swap; at any
                    // other angle fall back to a region so copper is
                    // never silently resized.
                    let q = ((comp.theta / std::f64::consts::FRAC_PI_2).round()
                        * std::f64::consts::FRAC_PI_2
                        - comp.theta)
                        .abs();
                    if q < 1e-6 {
                        let quarter = ((comp.theta / std::f64::consts::FRAC_PI_2)
                            .round() as i64)
                            .rem_euclid(2);
                        let (w, h) = if quarter == 1 {
                            (pad.height_mm, pad.width_mm)
                        } else {
                            (pad.width_mm, pad.height_mm)
                        };
                        let d = ap.obround(w, h);
                        let _ = writeln!(
                            pad_body,
                            "D{d}*\nX{}Y{}D03*",
                            coord(gx),
                            coord(cy(gy))
                        );
                    } else {
                        let pts = rotated_rect_corners(
                            gx,
                            gy,
                            pad.width_mm,
                            pad.height_mm,
                            comp.theta,
                        );
                        pad_body.push_str(&region(&pts));
                    }
                }
                PadShapeKind::Rect | PadShapeKind::RoundRect => {
                    let q = ((comp.theta / std::f64::consts::FRAC_PI_2).round()
                        * std::f64::consts::FRAC_PI_2
                        - comp.theta)
                        .abs();
                    if q < 1e-6 {
                        let quarter = ((comp.theta / std::f64::consts::FRAC_PI_2)
                            .round() as i64)
                            .rem_euclid(2);
                        let (w, h) = if quarter == 1 {
                            (pad.height_mm, pad.width_mm)
                        } else {
                            (pad.width_mm, pad.height_mm)
                        };
                        let d = ap.rect(w, h);
                        let _ = writeln!(
                            pad_body,
                            "D{d}*\nX{}Y{}D03*",
                            coord(gx),
                            coord(cy(gy))
                        );
                    } else {
                        let pts = rotated_rect_corners(
                            gx,
                            gy,
                            pad.width_mm,
                            pad.height_mm,
                            comp.theta,
                        );
                        pad_body.push_str(&region(&pts));
                    }
                }
            }
        }
    }
    body.push_str(&pad_body);

    // Mounting-hole annuli: the KiCad writer gives each hole a pad of
    // drill + 0.5mm, and that copper is real on every layer.
    let mut mh_body = String::new();
    for hole in &board.config.mounting_holes {
        let d = ap.circle(hole.drill_mm + 0.5);
        let _ = writeln!(
            mh_body,
            "D{d}*\nX{}Y{}D03*",
            coord(hole.x_mm),
            coord(cy(hole.y_mm))
        );
    }
    body.push_str(&mh_body);

    // Zone/pour copper — the writer's own polygons, not a mirror of
    // them. Each fractured polygon (holes joined to the outline by
    // zero-width slits, exactly as KiCad stores them) becomes one
    // Gerber region.
    let mut zone_body = String::new();
    for zf in &fills.zones {
        if zf.layer != layer {
            continue;
        }
        for poly in &zf.polys {
            if poly.len() >= 3 {
                zone_body.push_str(&region(poly));
            }
        }
    }
    body.push_str(&zone_body);

    let mut s = header(name);
    s.push_str(&ap.emit());
    s.push_str(&body);
    s.push_str("M02*\n");
    GerberFile { filename: format!("{name}.gbr"), contents: s }
}

/// Board outline (Edge.Cuts).
fn edge_cuts(board: &Board) -> GerberFile {
    let mut ap = Apertures::new();
    let d = ap.circle(0.05);
    let pts: Vec<(f64, f64)> = match &board.config.outline {
        BoardOutline::Polygon(p) => p.clone(),
        _ => {
            let (w, h) = (board.config.outline.width(), board.config.outline.height());
            vec![(0.0, 0.0), (w, 0.0), (w, h), (0.0, h)]
        }
    };
    let mut body = String::new();
    let _ = writeln!(body, "D{d}*");
    if !pts.is_empty() {
        let _ = writeln!(body, "X{}Y{}D02*", coord(pts[0].0), coord(cy(pts[0].1)));
        for p in pts.iter().skip(1) {
            let _ = writeln!(body, "X{}Y{}D01*", coord(p.0), coord(cy(p.1)));
        }
        let _ = writeln!(body, "X{}Y{}D01*", coord(pts[0].0), coord(cy(pts[0].1)));
    }
    let mut s = header("Edge_Cuts");
    s.push_str(&ap.emit());
    s.push_str(&body);
    s.push_str("M02*\n");
    GerberFile { filename: "Edge_Cuts.gbr".into(), contents: s }
}

/// Excellon drill file: every via barrel and through-hole pad,
/// grouped into tools by diameter.
fn excellon(board: &Board, routes: &[Route]) -> GerberFile {
    let mut tools: BTreeMap<String, Vec<(f64, f64)>> = BTreeMap::new();
    let vd = format!("{:.3}", board.layer_stack.via.drill_mm);
    for r in routes {
        for v in &r.vias {
            tools.entry(vd.clone()).or_default().push((v.x, v.y));
        }
    }
    for comp in &board.components {
        let (co, sn) = (comp.theta.cos(), comp.theta.sin());
        for pin in &comp.pins {
            if pin.unplaced {
                continue;
            }
            let Some(pad) = &pin.pad else { continue };
            let Some(drill) = pad.drill_mm else { continue };
            tools.entry(format!("{:.3}", drill)).or_default().push((
                comp.x + pin.dx * co - pin.dy * sn,
                comp.y + pin.dx * sn + pin.dy * co,
            ));
        }
    }
    for hole in &board.config.mounting_holes {
        tools
            .entry(format!("{:.3}", hole.drill_mm))
            .or_default()
            .push((hole.x_mm, hole.y_mm));
    }

    let mut s = String::new();
    s.push_str("M48\n");
    s.push_str("; Excellon drill file generated by bhdl\n");
    s.push_str("FMAT,2\n");
    s.push_str("METRIC,TZ\n");
    let names: Vec<&String> = tools.keys().collect();
    for (i, dia) in names.iter().enumerate() {
        let _ = writeln!(s, "T{}C{}", i + 1, dia);
    }
    s.push_str("%\n");
    s.push_str("G90\n");
    s.push_str("G05\n");
    for (i, dia) in names.iter().enumerate() {
        let _ = writeln!(s, "T{}", i + 1);
        for (x, y) in &tools[*dia] {
            let _ = writeln!(s, "X{:.3}Y{:.3}", x, cy(*y));
        }
    }
    s.push_str("T0\n");
    s.push_str("M30\n");
    GerberFile { filename: "drill.drl".into(), contents: s }
}

/// Build the full package for a placed-and-routed board.
pub fn export_fab(
    board: &Board,
    routes: &[Route],
    fills: &crate::output::kicad::BoardFills,
) -> FabPackage {
    let mut gerbers = Vec::new();
    for (i, layer) in board.layer_stack.layers.iter().enumerate() {
        if layer.kind != LayerKind::Signal {
            continue;
        }
        let name = layer.name.replace('.', "_");
        gerbers.push(copper_layer(board, routes, fills, i, &name));
    }
    gerbers.push(edge_cuts(board));
    let drill = excellon(board, routes);

    let n_tracks: usize = routes.iter().map(|r| r.segments.len()).sum();
    let n_vias: usize = routes.iter().map(|r| r.vias.len()).sum();
    let poured: Vec<&str> = board
        .nets
        .iter()
        .filter(|n| n.plane_layer.is_some())
        .map(|n| n.name.as_str())
        .collect();
    let mut manifest = String::new();
    manifest.push_str("bhdl fabrication package\n");
    manifest.push_str("========================\n\n");
    let _ = writeln!(manifest, "tracks: {n_tracks}\nvias:   {n_vias}");
    let _ = writeln!(
        manifest,
        "board:  {:.2} x {:.2} mm",
        board.config.outline.width(),
        board.config.outline.height()
    );
    manifest.push_str("\nFiles:\n");
    for g in &gerbers {
        let _ = writeln!(manifest, "  {}", g.filename);
    }
    let _ = writeln!(manifest, "  {}", drill.filename);
    let n_zone_polys: usize = fills.zones.iter().map(|z| z.polys.len()).sum();
    let _ = writeln!(manifest, "zones:  {n_zone_polys} filled polygon(s)");
    if !poured.is_empty() {
        manifest.push_str("\nPoured nets (zone copper included):\n");
        for p in &poured {
            let _ = writeln!(manifest, "  - {p}");
        }
    }
    FabPackage { gerbers, drill, manifest }
}
