//! The SAFETY-CASE capstone report (spec §2.14) — the `pdreport`
//! analog for the assessor: one markdown document assembling what the
//! machine MEASURED (the fault universe, metrics, PDN discharge,
//! DFA), what was CLAIMED (vendor DC, FIT sources), and what remains
//! OPEN (gaps, assumptions, dispositions). It renders the model — it
//! never re-derives: every number here was computed by the safety
//! flow that called it, and the same source regenerates the same
//! report byte-for-byte.

use crate::dfa::DfaFinding;
use bhdl_common::safety::{AssumptionStatus, MechanismKind, PartData, SafetyModel};
use std::fmt::Write as _;

/// Strip ANSI color escapes (the PDN lines are terminal-colored).
fn plain(s: &str) -> String {
    let mut out = String::new();
    let mut chars = s.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '\u{1b}' {
            while let Some(&n) = chars.peek() {
                chars.next();
                if n == 'm' {
                    break;
                }
            }
        } else {
            out.push(c);
        }
    }
    out
}

fn esc(s: &str) -> String {
    s.replace('|', "\\|")
}

pub fn render(
    model: &SafetyModel,
    pdn_lines: &[String],
    dfa: &[DfaFinding],
    source_name: &str,
) -> String {
    let mut o = String::new();
    let w = &mut o;
    let _ = writeln!(w, "# Safety case — {}", model.board);
    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "_Generated by `bhdl safety --report` from `{source_name}`. Deterministic: the same source regenerates this document byte-for-byte. Every number below was MEASURED by the fault campaign or carries its named source; absences are stated as gaps, never defaulted._"
    );

    // ── 1 Mission & scope ────────────────────────────────────────────
    let _ = writeln!(w, "\n## 1 Mission profile & scope");
    match &model.mission {
        Some(m) => {
            let _ = writeln!(
                w,
                "- ambient: {} °C{}; lifetime: {}{}",
                m.ambient_c,
                m.profile.as_deref().map(|p| format!(" (time-weighted mean of profile `{p}`)")).unwrap_or_default(),
                m.lifetime_h.map(|h| format!("{h} h")).unwrap_or_else(|| "UNDECLARED — PMHF stays the single-point approximation, stated".into()),
                m.time_basis.as_deref().map(|b| format!("; λ basis: {b}")).unwrap_or_default(),
            );
            if !m.phases.is_empty() {
                let _ = writeln!(w, "\n| phase | life | ambient | powered |");
                let _ = writeln!(w, "|---|---|---|---|");
                for ph in &m.phases {
                    let _ = writeln!(
                        w,
                        "| {} | {:.1}% | {:.0} °C | {} |",
                        esc(&ph.name),
                        ph.frac * 100.0,
                        ph.ambient_c,
                        if ph.powered { "yes" } else { "no — contributes no operating λ (no dormant term in the shipped models, stated)" },
                    );
                }
                let _ = writeln!(
                    w,
                    "\n_Part FITs below are the time-weighted λ over the powered phases (each part's basis string shows the per-phase composition)._"
                );
            }
        }
        None => {
            let _ = writeln!(w, "- mission profile UNDECLARED — handbook FITs and the dual-point PMHF term cannot be computed (gap)");
        }
    }
    let _ = writeln!(
        w,
        "- scope, stated: single-fault universe + latent double-probe + fault-at-boot timeline + PDN recheck; structural DFA (no quantified β, no layout proximity, no shared clocks); the PWL and SPICE engines' model scopes apply to their verdicts."
    );

    // ── 2 Safety goals ───────────────────────────────────────────────
    let _ = writeln!(w, "\n## 2 Safety goals");
    for sc in &model.scopes {
        let label = if sc.path.is_empty() { format!("board ({})", sc.ns) } else { format!("{} ({})", sc.path, sc.ns) };
        if sc.goals.is_empty() {
            continue;
        }
        let _ = writeln!(w, "\n### {label}");
        let _ = writeln!(w, "| goal | level | id | FTTI | safe state | refines |");
        let _ = writeln!(w, "|---|---|---|---|---|---|");
        for g in &sc.goals {
            let _ = writeln!(
                w,
                "| {} | {} | {} | {} | {} | {} |",
                esc(&g.path),
                g.level.as_str(),
                g.id.as_deref().unwrap_or("—"),
                g.ftti.as_deref().unwrap_or("—"),
                esc(g.safe_state.as_deref().unwrap_or("—")),
                g.refines.as_deref().unwrap_or("—"),
            );
        }
        let _ = writeln!(w, "\n| effect | predicate (verbatim) | severity |");
        let _ = writeln!(w, "|---|---|---|");
        for g in &sc.goals {
            for e in &g.effects {
                let _ = writeln!(w, "| {}.{} | `{}` | {} |", esc(&g.path), esc(&e.name), esc(&e.expr), e.severity.as_str());
            }
        }
    }

    // ── 3 Mechanisms ─────────────────────────────────────────────────
    let _ = writeln!(w, "\n## 3 Safety mechanisms — claimed vs measured");
    let _ = writeln!(w, "| mechanism | kind | goal | claimed DC (source) | MEASURED DC | detected_when |");
    let _ = writeln!(w, "|---|---|---|---|---|---|");
    for sc in &model.scopes {
        for m in &sc.mechanisms {
            let claimed = match (m.claimed_dc, &m.dc_source) {
                (Some(dc), Some(src)) => format!("{:.0}% ({})", dc * 100.0, esc(src)),
                (Some(dc), None) => format!("{:.0}% (UNSOURCED — gap)", dc * 100.0),
                _ => "—".into(),
            };
            let measured = match m.measured_dc {
                Some(dc) => format!("{:.1}%", dc * 100.0),
                None => "not measured".into(),
            };
            let _ = writeln!(
                w,
                "| {} | {} | {} | {} | {} | {} |",
                esc(&m.handle),
                match m.kind { MechanismKind::Psm => "PSM", MechanismKind::Lsm => "LSM" },
                esc(&m.goal),
                claimed,
                measured,
                m.detected_when.as_deref().map(|d| format!("`{}`", esc(d))).unwrap_or_else(|| "— (no measured DC possible)".into()),
            );
        }
    }
    let _ = writeln!(w, "\n_Measured DC wins over claimed wherever both exist; the measurement basis is in the FMEDA package._");

    // ── 4 Parts & failure data ───────────────────────────────────────
    let _ = writeln!(w, "\n## 4 Parts and failure data");
    let (mut n_beh, mut n_seooc, mut n_hand, mut n_waived, mut n_none) = (0, 0, 0, 0, 0);
    for p in &model.parts {
        match &p.data {
            PartData::Behavioral { .. } => n_beh += 1,
            PartData::Seooc { .. } => n_seooc += 1,
            PartData::Handbook { .. } => n_hand += 1,
            PartData::Waived { .. } => n_waived += 1,
            PartData::None => n_none += 1,
        }
    }
    let _ = writeln!(
        w,
        "{} part(s): {n_beh} behavioral (vendor failure states), {n_seooc} SEooC, {n_hand} handbook-FIT, {n_waived} waived, {n_none} with NO safety data (each is a PART_NO_SAFETY_DATA gap).",
        model.parts.len()
    );
    let _ = writeln!(w, "\n| instance | type | data | FIT (basis) |");
    let _ = writeln!(w, "|---|---|---|---|");
    for p in &model.parts {
        let (data, fit) = match &p.data {
            PartData::Behavioral { failure_states, source, .. } => (format!("behavioral, {failure_states} state(s) ({})", esc(source)), "per-state λ".to_string()),
            PartData::Seooc { lambda_fit, source } => ("SEooC".into(), format!("{} ({})", lambda_fit.map(|l| format!("{l:.1}")).unwrap_or_else(|| "—".into()), esc(source))),
            PartData::Handbook { class, source, fit, fit_basis, .. } => (
                format!("handbook: {} ({})", esc(class), esc(source)),
                match (fit, fit_basis) {
                    (Some(f), Some(b)) => format!("{f:.2} ({})", esc(b)),
                    (Some(f), None) => format!("{f:.2}"),
                    _ => "NOT COMPUTED (gap)".into(),
                },
            ),
            PartData::Waived { reason } => (format!("waived: {}", esc(reason)), "—".into()),
            PartData::None => ("NO SAFETY DATA (gap)".into(), "—".into()),
        };
        let _ = writeln!(w, "| {} | {} | {} | {} |", esc(&p.instance), esc(&p.type_name), data, fit);
    }

    // ── 5 Fault universe (measured) ──────────────────────────────────
    let _ = writeln!(w, "\n## 5 Fault universe — measured campaign");
    let ran = model.universe.iter().filter(|u| u.ran).count();
    let dang: Vec<_> = model.universe.iter().filter(|u| u.ran && !u.fired.is_empty()).collect();
    let resid = dang.iter().filter(|u| u.detected.is_empty()).count();
    let fa = model.universe.iter().filter(|u| u.false_alarm).count();
    let latent = model.universe.iter().filter(|u| u.latent).count();
    let _ = writeln!(
        w,
        "{} fault(s): {ran} ran, {} dangerous ({resid} residual), {fa} false alarm(s), {latent} latent. Synthetic effects: `pdn:` = dynamic PDN-contract violation (recheck), `boot:` = start-up contract violation (fault-at-boot timeline); `(transient)` detection was measured over the faulted transient samples.",
        model.universe.len(),
        dang.len(),
    );
    if !dang.is_empty() {
        let _ = writeln!(w, "\n| fault | fired | detected | note |");
        let _ = writeln!(w, "|---|---|---|---|");
        for u in &dang {
            let _ = writeln!(
                w,
                "| {} {}({}) | {} | {} | {} |",
                esc(&u.part),
                esc(&u.mode),
                esc(&u.targets.join(", ")),
                esc(&u.fired.join(", ")),
                if u.detected.is_empty() { "**RESIDUAL**".into() } else { esc(&u.detected.join(", ")) },
                esc(u.note.as_deref().unwrap_or("—")),
            );
        }
    }
    let unrun: Vec<_> = model.universe.iter().filter(|u| !u.ran).collect();
    if !unrun.is_empty() {
        let _ = writeln!(w, "\n{} fault(s) did NOT run (each carries its reason in the FMEDA worksheet) — the metrics section counts them unmeasured.", unrun.len());
    }

    // ── 6 Metrics ────────────────────────────────────────────────────
    let _ = writeln!(w, "\n## 6 Hardware architectural metrics");
    let mut any = false;
    for sc in &model.scopes {
        if let Some(m) = &sc.metrics {
            any = true;
            let label = if sc.path.is_empty() { "board".to_string() } else { sc.path.clone() };
            let _ = writeln!(
                w,
                "- **{label}**: SPFM {:.1}% | LFM {:.1}% | PMHF {:.3} FIT — λ_total {:.1} FIT over {} measured fault(s), {} unmeasured{}",
                m.spfm * 100.0,
                m.lfm * 100.0,
                m.pmhf_fit,
                m.lambda_total_fit,
                model.universe.iter().filter(|u| u.ran && u.weight_fit.is_some()).count(),
                m.unmeasured_faults,
                if m.unmeasured_faults > 0 { " (metrics cannot PASS until the whole universe is measured)" } else { "" },
            );
        }
    }
    if !any {
        let _ = writeln!(w, "not computed — the fault universe has not run (stated).");
    }
    let _ = writeln!(
        w,
        "- overall verdict: **{}**",
        if model.verdict_pass() { "PASS" } else { "FAIL — see the gap register" }
    );

    // ── 7 PDN contract ───────────────────────────────────────────────
    if !pdn_lines.is_empty() {
        let _ = writeln!(w, "\n## 7 PDN contract — machine verification");
        let _ = writeln!(w, "_The `assume pdn(...)` assumptions of use are discharged by these checks; a violated check keeps its assumption OPEN._\n");
        let _ = writeln!(w, "```");
        for l in pdn_lines {
            let _ = writeln!(w, "{}", plain(l));
        }
        let _ = writeln!(w, "```");
    }

    // ── 8 DFA ────────────────────────────────────────────────────────
    let _ = writeln!(w, "\n## 8 Dependent-failure analysis (ISO 26262-9 shape)");
    if dfa.is_empty() {
        let _ = writeln!(w, "no initiators found by the structural walks (scope as stated in §1).");
    } else {
        let _ = writeln!(w, "| class | severity | subject | finding | disposition |");
        let _ = writeln!(w, "|---|---|---|---|---|");
        for f in dfa {
            let _ = writeln!(
                w,
                "| {} | {} | {} | {} | {} |",
                f.class,
                if f.strong { "**strong**" } else { "info" },
                esc(&f.subject),
                esc(&f.text),
                if f.strong { "OPEN — design review" } else { "note — review argument" },
            );
        }
    }

    // ── 9 Assumptions of use ─────────────────────────────────────────
    let _ = writeln!(w, "\n## 9 Assumptions of use");
    let mut any_a = false;
    for sc in &model.scopes {
        for a in &sc.assumptions {
            any_a = true;
            let status = match &a.status {
                AssumptionStatus::Open => "**OPEN**".to_string(),
                AssumptionStatus::SatisfiedBy(x) => format!("satisfied: {}", esc(x)),
                AssumptionStatus::Waived(r) => format!("waived: {}", esc(r)),
            };
            let _ = writeln!(w, "- `{}` — {} — {}", esc(&a.id), esc(&a.text), status);
        }
    }
    if !any_a {
        let _ = writeln!(w, "none declared.");
    }

    // ── 10 Gap register ──────────────────────────────────────────────
    let _ = writeln!(w, "\n## 10 Gap register — the assessor's to-do");
    if model.gaps.is_empty() {
        let _ = writeln!(w, "no open gaps.");
    } else {
        let _ = writeln!(w, "| class | goal | subject | fix |");
        let _ = writeln!(w, "|---|---|---|---|");
        for g in &model.gaps {
            let _ = writeln!(
                w,
                "| {} | {} | {} | {} |",
                g.class.as_str(),
                esc(if g.goal.is_empty() { "—" } else { &g.goal }),
                esc(&g.subject),
                esc(&g.fix),
            );
        }
    }
    o
}
