[package]
name = "bhdl-visualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bhdl-netlist = { path = "../bhdl-netlist" }
bhdl-synthesizer = { path = "../bhdl-synthesizer" }
bhdl-components = { path = "../bhdl-components" }
bhdl-analyzer = { path = "../bhdl-analyzer" }
bhdl-parser = { path = "../bhdl-parser" }
bhdl-ast = { path = "../bhdl-ast" }
bhdl-common = { path = "../bhdl-common" }
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"
tokio = { version = "1.0", features = ["rt", "rt-multi-thread", "macros"] }
regex = "1.0"
svg = "0.16.0"
quick-xml = { version = "0.31", features = ["serialize"] }
getrandom = { version = "0.2", features = ["js"] }
rand = "0.8"
petgraph = "0.6.4"
rayon = "1.8.1"
ordered-float = "2.10"
slotmap = { version = "1", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
tempfile = "3.0"
tokio-test = "0.4"

[lib]
name = "bhdl_visualizer"
path = "src/lib.rs"

[[bin]]
name = "test_ascii"
path = "src/bin/test_ascii.rs"
