//! BHDL emitter.
//!
//! Phase D of the KiCad-to-BHDL translator (plan §5.4). Consumes
//! a parsed [`Schematic`], the per-sheet [`NetList`]s produced by
//! [`crate::nets::extract_nets`], and the
//! [`crate::symbol_mapping::MappingRegistry`], and produces a
//! `.bhdl` source string.
//!
//! ## Hierarchy
//!
//! The root sheet emits a top-level `board` block. Each child
//! sheet emits an `entity` block alongside, with the child's
//! hierarchical labels surfaced as ports. The board block
//! instantiates each subsheet exactly where it appeared in the
//! parent — one entity instance per `(sheet ...)` reference, so
//! reused sub-circuits collapse naturally to multiple instances of
//! the same entity.
//!
//! ## Power and globals
//!
//! Power-flag symbols (`+5V`, `GND`, …) become `power NAME = …;`
//! / `ground NAME;` declarations on the board, and references to
//! them in pin connections use the bare name (no `@` prefix).
//! Local nets get an `@` prefix; unnamed local nets are emitted as
//! `@Net_<n>`.
//!
//! ## Unmapped symbols
//!
//! KiCad lib_ids that aren't in the mapping registry fall through
//! to the `kicad_passthrough` entity — a placeholder that carries
//! the KiCad reference designator + value + footprint as
//! attributes so the import never aborts on an unknown part. The
//! "enrich" phase upgrades these to real stdlib entries one
//! library at a time.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

use crate::ir::{PowerCategory, Sheet, Schematic};
use crate::nets::{extract_nets, Net, NetList};
use crate::symbol_mapping::MappingRegistry;

/// Errors specific to BHDL emission.
#[derive(Debug, thiserror::Error)]
pub enum EmitError {
    #[error("formatting error: {0}")]
    Fmt(#[from] std::fmt::Error),
}

/// Output of the emitter — one BHDL source string covering the
/// whole schematic (board + nested entity definitions).
pub struct EmittedBhdl {
    pub board_name: String,
    pub source: String,
    /// Diagnostics gathered during emission. Non-fatal: each one
    /// names a symbol or net that the importer couldn't fully
    /// resolve, so reviewers know what to enrich.
    pub warnings: Vec<String>,
}

/// Main entry point. `board_name` is the identifier used for the
/// top-level `board` block (typically the .kicad_sch filename
/// without extension, but the caller decides).
pub fn emit_bhdl(
    schematic: &Schematic,
    mapping: &MappingRegistry,
    board_name: &str,
) -> Result<EmittedBhdl, EmitError> {
    let mut out = String::new();
    let mut warnings = Vec::new();
    let board_ident = sanitise_ident(board_name);

    // ── header ────────────────────────────────────────────────
    writeln!(out, "// Auto-generated by bhdl-kicad-import from {}.",
        schematic.root.path.display())?;
    writeln!(out, "// KiCad generator: {} (format version {})",
        schematic.generator, schematic.version)?;
    writeln!(out, "// Edit freely — re-running the importer will preserve user changes")?;
    writeln!(out, "// only if you keep the section markers intact.")?;
    writeln!(out)?;

    // ── child sheets first (so they're defined before use) ────
    // Stable iteration order: BTreeMap of sheet path → Sheet.
    let mut child_sheets: BTreeMap<&std::path::Path, &Sheet> = BTreeMap::new();
    for (path, sheet) in &schematic.child_sheets {
        child_sheets.insert(path.as_path(), sheet);
    }
    for (path, sheet) in &child_sheets {
        let ent_name = sheet_entity_name(path);
        emit_subsheet_entity(&mut out, &ent_name, sheet, mapping, &mut warnings)?;
        writeln!(out)?;
    }

    // ── top-level board ───────────────────────────────────────
    emit_board(&mut out, &board_ident, schematic, mapping, &mut warnings)?;

    Ok(EmittedBhdl { board_name: board_ident, source: out, warnings })
}

// ──────────────────────────────────────────────────────────────
// Board emission
// ──────────────────────────────────────────────────────────────

fn emit_board(
    out: &mut String,
    board_ident: &str,
    schematic: &Schematic,
    mapping: &MappingRegistry,
    warnings: &mut Vec<String>,
) -> Result<(), EmitError> {
    let sheet = &schematic.root;
    let nets = extract_nets(sheet);

    writeln!(out, "board {} {{", board_ident)?;

    // Power & ground declarations (one per distinct power-net name).
    emit_power_decls(out, sheet, &nets)?;
    writeln!(out)?;

    // Component instances.
    emit_component_decls(out, sheet, mapping, warnings)?;
    writeln!(out)?;

    // Subsheet instances.
    if !schematic.child_sheets.is_empty() {
        writeln!(out, "    // Hierarchical subsheets")?;
        for sr in &sheet.sheet_refs {
            let ent_name = sheet_entity_name(&sr.file_path);
            let inst_name = sanitise_ident(&sr.name);
            writeln!(out, "    {}: {}();", inst_name, ent_name)?;
        }
        writeln!(out)?;
        // Connections from the parent into each subsheet's ports
        // (one per sheet pin → net mapping).
        emit_subsheet_connections(out, sheet, &nets)?;
        writeln!(out)?;
    }

    // Net connections.
    emit_net_connections(out, &nets, sheet)?;

    writeln!(out, "}}")?;
    Ok(())
}

// ──────────────────────────────────────────────────────────────
// Subsheet (entity) emission
// ──────────────────────────────────────────────────────────────

fn emit_subsheet_entity(
    out: &mut String,
    entity_name: &str,
    sheet: &Sheet,
    mapping: &MappingRegistry,
    warnings: &mut Vec<String>,
) -> Result<(), EmitError> {
    let nets = extract_nets(sheet);

    // Ports come from hierarchical labels — these are the
    // schematic's stated interface to the parent.
    let mut port_names: BTreeSet<String> = BTreeSet::new();
    for hl in &sheet.hierarchical_labels {
        port_names.insert(sanitise_ident(&hl.text));
    }

    write!(out, "entity {}(", entity_name)?;
    let mut first = true;
    for p in &port_names {
        if !first { write!(out, ", ")?; }
        write!(out, "{}: signal inout", p)?;
        first = false;
    }
    writeln!(out, ") {{")?;

    // Power decls (still local to the subsheet — power flags in a
    // child sheet are conceptually local power references that
    // happen to share a name with the parent's rails).
    emit_power_decls(out, sheet, &nets)?;
    writeln!(out)?;

    emit_component_decls(out, sheet, mapping, warnings)?;
    writeln!(out)?;
    emit_net_connections(out, &nets, sheet)?;

    writeln!(out, "}}")?;
    Ok(())
}

// ──────────────────────────────────────────────────────────────
// Shared emission helpers
// ──────────────────────────────────────────────────────────────

fn emit_power_decls(out: &mut String, sheet: &Sheet, nets: &NetList) -> Result<(), EmitError> {
    // Collect power-net names that the net-extractor identified.
    // Cross-reference with PowerSymbol categories from the IR so
    // we know which ones are grounds vs supplies.
    let mut emitted: BTreeSet<String> = BTreeSet::new();
    for net in &nets.nets {
        if !net.is_power || !emitted.insert(net.name.clone()) { continue; }
        // Find a power symbol matching this net to pull its
        // category/voltage.
        let ps = sheet.power_symbols.iter().find(|p| {
            let canon = crate::nets::canonical_power_name_for_test(&p.label, p.category);
            canon == net.name
        });
        match ps {
            Some(p) if p.category == PowerCategory::Ground => {
                writeln!(out, "    ground {};", net.name)?;
            }
            Some(p) => {
                if let Some(v) = p.voltage {
                    writeln!(out, "    power {} = {}V;", net.name, format_num(v))?;
                } else {
                    writeln!(out, "    power {};", net.name)?;
                }
            }
            None => {
                writeln!(out, "    power {};", net.name)?;
            }
        }
    }
    Ok(())
}

fn emit_component_decls(
    out: &mut String,
    sheet: &Sheet,
    mapping: &MappingRegistry,
    warnings: &mut Vec<String>,
) -> Result<(), EmitError> {
    writeln!(out, "    // Components")?;
    for sym in &sheet.symbols {
        // Power flags are *not* component instances; their
        // contribution is the net name they bestow.
        if sym.lib_id.starts_with("power:") {
            continue;
        }
        let m = mapping.lookup(&sym.lib_id);
        let entity_name = match m {
            Some(m) if !m.is_power_net() => m.bhdl.as_str(),
            _ => {
                warnings.push(format!(
                    "unmapped KiCad symbol {:?} (ref={}); falling back to kicad_passthrough",
                    sym.lib_id,
                    sym.reference().unwrap_or("?"),
                ));
                "kicad_passthrough"
            }
        };
        let inst_ident = sanitise_ident(sym.reference().unwrap_or("U_unknown"));
        let value = sym.value().unwrap_or("").trim();
        let arg = if value.is_empty() || value == sym.reference().unwrap_or("") {
            String::new()
        } else {
            format!("\"{}\"", value.replace('"', "\\\""))
        };
        writeln!(out, "    {}: {}({});", inst_ident, entity_name, arg)?;
    }
    Ok(())
}

fn emit_net_connections(out: &mut String, nets: &NetList, sheet: &Sheet) -> Result<(), EmitError> {
    writeln!(out, "    // Connections")?;
    // Map symbol UUID → reference designator (for emit).
    let mut ref_of: BTreeMap<&str, String> = BTreeMap::new();
    for sym in &sheet.symbols {
        let r = sanitise_ident(sym.reference().unwrap_or("U_unknown"));
        ref_of.insert(sym.uuid.as_str(), r);
    }

    for net in &nets.nets {
        if net.pins.is_empty() { continue; }
        let net_ref = net_reference(net);
        for pin in &net.pins {
            let inst = ref_of.get(pin.symbol_uuid.as_str())
                .cloned()
                .unwrap_or_else(|| "U_unknown".into());
            writeln!(out, "    {} -> {}.{};", net_ref, inst, pin.pin_number)?;
        }
    }
    Ok(())
}

fn emit_subsheet_connections(out: &mut String, sheet: &Sheet, nets: &NetList) -> Result<(), EmitError> {
    writeln!(out, "    // Sheet-pin connections (parent ↔ subsheet ports)")?;
    for sr in &sheet.sheet_refs {
        let inst_name = sanitise_ident(&sr.name);
        for sp in &sr.pins {
            // Find which net this sheet pin sits on. The
            // net-extractor interned the sheet-pin coordinate but
            // didn't register the sheet pin as a NetPin, so we
            // recover the net by coordinate match.
            let port = sanitise_ident(&sp.name);
            let net_name = find_net_at(nets, sheet, (sp.at.0, sp.at.1))
                .map(|n| net_reference(n))
                .unwrap_or_else(|| format!("@unconnected_{}", port));
            writeln!(out, "    {} -> {}.{};", net_name, inst_name, port)?;
        }
    }
    Ok(())
}

// ──────────────────────────────────────────────────────────────
// Naming helpers
// ──────────────────────────────────────────────────────────────

/// How to reference a net in connection lines. Power nets use
/// the bare name; local nets get an `@` prefix.
fn net_reference(net: &Net) -> String {
    if net.is_power { net.name.clone() } else { format!("@{}", net.name) }
}

/// Map a child sheet's on-disk path to a BHDL entity name.
fn sheet_entity_name(path: &std::path::Path) -> String {
    let stem = path.file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("subsheet");
    sanitise_ident(stem)
}

/// Sanitise a raw KiCad string (reference, sheet name, port name)
/// to a valid BHDL identifier. Replaces non-alnum chars with `_`,
/// prefixes with `_` if the first char is a digit.
fn sanitise_ident(raw: &str) -> String {
    if raw.is_empty() { return "_".to_string(); }
    let mut out: String = raw.chars().map(|c| {
        if c.is_ascii_alphanumeric() || c == '_' { c } else { '_' }
    }).collect();
    if out.chars().next().unwrap().is_ascii_digit() {
        out.insert(0, '_');
    }
    out
}

/// Format a floating-point voltage compactly: integers as integer,
/// fractions to up to 3 decimal places.
fn format_num(v: f64) -> String {
    if (v - v.round()).abs() < 1e-6 {
        format!("{}", v.round() as i64)
    } else {
        let s = format!("{:.3}", v);
        // Trim trailing zeroes from the fractional part.
        let s = s.trim_end_matches('0').trim_end_matches('.');
        s.to_string()
    }
}

/// Look up which net a coordinate lands on. Used for sheet-pin →
/// net resolution. Linear search through `nets.nets[*].pins` is
/// too coarse (pins record symbol UUID, not coordinate), so we go
/// through the sheet's pin_positions and find the matching pin.
fn find_net_at<'a>(nets: &'a NetList, sheet: &Sheet, at: (f64, f64)) -> Option<&'a Net> {
    // Find a pin position close to `at`; then locate the net it
    // belongs to via symbol_uuid + pin_number.
    const EPS: f64 = 0.01; // 10 µm
    for sym in &sheet.symbols {
        for pp in &sym.pin_positions {
            if (pp.at.0 - at.0).abs() < EPS && (pp.at.1 - at.1).abs() < EPS {
                return nets.nets.iter().find(|n| n.pins.iter()
                    .any(|p| p.symbol_uuid == sym.uuid && p.pin_number == pp.pin_number));
            }
        }
    }
    // Fallback: sheet pins sit at the edge of the subsheet symbol;
    // a wire from the parent ought to terminate exactly there. We
    // don't have a pin record at that exact spot, so we can't
    // resolve the net deterministically — caller will use the
    // unconnected stub.
    None
}
