//! BHDL emitter.
//!
//! Phase D of the KiCad-to-BHDL translator (plan §5.4). Consumes
//! a parsed [`Schematic`], the per-sheet [`NetList`]s produced by
//! [`crate::nets::extract_nets`], and the
//! [`crate::symbol_mapping::MappingRegistry`], and produces a
//! `.bhdl` source string.
//!
//! ## Hierarchy
//!
//! The root sheet emits a top-level `board` block. Each child
//! sheet emits an `entity` block alongside, with the child's
//! hierarchical labels surfaced as ports. The board block
//! instantiates each subsheet exactly where it appeared in the
//! parent — one entity instance per `(sheet ...)` reference, so
//! reused sub-circuits collapse naturally to multiple instances of
//! the same entity.
//!
//! ## Power and globals
//!
//! Power-flag symbols (`+5V`, `GND`, …) become `power NAME = …;`
//! / `ground NAME;` declarations on the board, and references to
//! them in pin connections use the bare name (no `@` prefix).
//! Local nets get an `@` prefix; unnamed local nets are emitted as
//! `@Net_<n>`.
//!
//! ## Unmapped symbols
//!
//! KiCad lib_ids that aren't in the mapping registry fall through
//! to the `kicad_passthrough` entity — a placeholder that carries
//! the KiCad reference designator + value + footprint as
//! attributes so the import never aborts on an unknown part. The
//! "enrich" phase upgrades these to real stdlib entries one
//! library at a time.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

use crate::ir::{PowerCategory, Sheet, Schematic};
use crate::nets::{extract_nets, Net, NetList};
use crate::symbol_mapping::MappingRegistry;

/// Errors specific to BHDL emission.
#[derive(Debug, thiserror::Error)]
pub enum EmitError {
    #[error("formatting error: {0}")]
    Fmt(#[from] std::fmt::Error),
}

/// Output of the emitter — one BHDL source string covering the
/// whole schematic (board + nested entity definitions).
pub struct EmittedBhdl {
    pub board_name: String,
    pub source: String,
    /// Diagnostics gathered during emission. Non-fatal: each one
    /// names a symbol or net that the importer couldn't fully
    /// resolve, so reviewers know what to enrich.
    pub warnings: Vec<String>,
}

/// Emission options. Use `EmitOptions::default()` for the
/// behaviour the older `emit_bhdl(...)` function had; set
/// `stdlib_path` when the emitted BHDL needs to compile through
/// `bhdl-synthesizer` (round-trip tests, real-world use).
#[derive(Debug, Clone, Default)]
pub struct EmitOptions {
    /// Path to `bhdl-stdlib/` on disk. When set, the emitter
    /// prepends `import { ... } from "<stdlib_path>/<rel>.bhdl";`
    /// lines for every stdlib entity referenced. When None, no
    /// import header is emitted (older callers, tests that
    /// don't care about parser-validity).
    pub stdlib_path: Option<std::path::PathBuf>,
}

/// Backwards-compatible entry point. Delegates to
/// `emit_bhdl_with_options(...)` with default options (no
/// imports emitted).
pub fn emit_bhdl(
    schematic: &Schematic,
    mapping: &MappingRegistry,
    board_name: &str,
) -> Result<EmittedBhdl, EmitError> {
    emit_bhdl_with_options(schematic, mapping, board_name, &EmitOptions::default())
}

/// Main entry point. `board_name` is the identifier used for the
/// top-level `board` block (typically the .kicad_sch filename
/// without extension, but the caller decides). `opts` carries
/// optional configuration like the stdlib search path for
/// import generation.
pub fn emit_bhdl_with_options(
    schematic: &Schematic,
    mapping: &MappingRegistry,
    board_name: &str,
    opts: &EmitOptions,
) -> Result<EmittedBhdl, EmitError> {
    let mut out = String::new();
    let mut warnings = Vec::new();
    let board_ident = sanitise_ident(board_name);

    // ── header ────────────────────────────────────────────────
    writeln!(out, "// Auto-generated by bhdl-kicad-import from {}.",
        schematic.root.path.display())?;
    writeln!(out, "// KiCad generator: {} (format version {})",
        schematic.generator, schematic.version)?;
    writeln!(out, "// Edit freely — re-running the importer will preserve user changes")?;
    writeln!(out, "// only if you keep the section markers intact.")?;
    writeln!(out)?;

    // ── imports ───────────────────────────────────────────────
    if let Some(stdlib_path) = &opts.stdlib_path {
        let used = collect_used_stdlib_entities(schematic, mapping);
        emit_imports(&mut out, stdlib_path, &used)?;
        writeln!(out)?;
    }

    // ── child sheets first (so they're defined before use) ────
    // Stable iteration order: BTreeMap of sheet path → Sheet.
    let mut child_sheets: BTreeMap<&std::path::Path, &Sheet> = BTreeMap::new();
    for (path, sheet) in &schematic.child_sheets {
        child_sheets.insert(path.as_path(), sheet);
    }
    for (path, sheet) in &child_sheets {
        let ent_name = sheet_entity_name(path);
        emit_subsheet_entity(&mut out, &ent_name, sheet, mapping, &mut warnings)?;
        writeln!(out)?;
    }

    // ── top-level board ───────────────────────────────────────
    emit_board(&mut out, &board_ident, schematic, mapping, &mut warnings)?;

    Ok(EmittedBhdl { board_name: board_ident, source: out, warnings })
}

// ──────────────────────────────────────────────────────────────
// Board emission
// ──────────────────────────────────────────────────────────────

fn emit_board(
    out: &mut String,
    board_ident: &str,
    schematic: &Schematic,
    mapping: &MappingRegistry,
    warnings: &mut Vec<String>,
) -> Result<(), EmitError> {
    let sheet = &schematic.root;
    let nets = extract_nets(sheet);

    writeln!(out, "board {} {{", board_ident)?;

    // Power & ground declarations (one per distinct power-net name).
    emit_power_decls(out, sheet, &nets)?;
    writeln!(out)?;

    // Component instances.
    emit_component_decls(out, sheet, mapping, warnings)?;
    writeln!(out)?;

    // Subsheet instances.
    if !schematic.child_sheets.is_empty() {
        writeln!(out, "    // Hierarchical subsheets")?;
        for sr in &sheet.sheet_refs {
            let ent_name = sheet_entity_name(&sr.file_path);
            let inst_name = sanitise_ident(&sr.name);
            writeln!(out, "    {}: {}();", inst_name, ent_name)?;
        }
        writeln!(out)?;
        // Connections from the parent into each subsheet's ports.
        // Two sources:
        //   (a) Sheet pins on the parent — explicit per-pin wiring
        //       to a hierarchical label inside the subsheet.
        //   (b) Power/ground nets the subsheet lifted to ports —
        //       wired to the board's own power-rail by name match.
        emit_subsheet_connections(out, sheet, &nets)?;
        emit_subsheet_power_wiring(out, schematic)?;
        writeln!(out)?;
    }

    // Net connections.
    emit_net_connections(out, &nets, sheet, mapping)?;

    writeln!(out, "}}")?;
    Ok(())
}

// ──────────────────────────────────────────────────────────────
// Subsheet (entity) emission
// ──────────────────────────────────────────────────────────────

/// One declared entity port — used by both the entity-signature
/// emitter and the parent's instance-wiring emitter so they
/// agree on the port set.
#[derive(Debug, Clone)]
struct EntityPort {
    /// BHDL port identifier (already sanitised).
    name: String,
    /// `signal inout` / `power in` / `ground in`. The classification
    /// comes from whether the net is power-typed in `NetList`.
    kind: &'static str,
    /// For power ports, the canonical power-net name on the parent
    /// (which the parent uses to wire the port). Equal to `name`
    /// for power nets; None for hierarchical-label ports.
    parent_net: Option<String>,
}

/// Compute the port list a subsheet exposes — both hierarchical
/// labels (signal ports) AND power-nets referenced inside (lifted
/// to power ports). KiCad treats power flags as implicit globals,
/// but BHDL `entity` blocks don't allow `power X = N V;` decls
/// inside, so we surface them as ports and let the parent board
/// wire them at instantiation time.
fn collect_entity_ports(sheet: &Sheet, nets: &NetList) -> Vec<EntityPort> {
    let mut ports: Vec<EntityPort> = Vec::new();
    let mut seen: BTreeSet<String> = BTreeSet::new();

    // Hierarchical labels first — the schematic's explicit
    // interface. Bidirectional signal ports.
    for hl in &sheet.hierarchical_labels {
        let name = sanitise_ident(&hl.text);
        if seen.insert(name.clone()) {
            ports.push(EntityPort {
                name,
                kind: "signal inout",
                parent_net: None,
            });
        }
    }

    // Power / ground nets actually referenced inside the sheet's
    // connections. These would otherwise be `power VCC_5V = 5V;`
    // / `ground GND;` decls — not allowed inside an entity body.
    for net in &nets.nets {
        if !net.is_power { continue; }
        // Skip nets with no pins on the subsheet (KiCad-side
        // ghosts that won't generate any connections inside).
        if net.pins.is_empty() { continue; }
        let port_name = sanitise_ident(&net.name);
        if !seen.insert(port_name.clone()) { continue; }
        // Distinguish ground vs supply by the matching PowerSymbol's
        // category. Default to `power in` if uncertain.
        let kind = sheet.power_symbols.iter().find(|p| {
            let canon = crate::nets::canonical_power_name_for_test(&p.label, p.category);
            canon == net.name
        }).map(|p| if p.category == PowerCategory::Ground {
            "ground in"
        } else {
            "power in"
        }).unwrap_or("power in");
        ports.push(EntityPort {
            name: port_name,
            kind,
            parent_net: Some(net.name.clone()),
        });
    }

    ports
}

fn emit_subsheet_entity(
    out: &mut String,
    entity_name: &str,
    sheet: &Sheet,
    mapping: &MappingRegistry,
    warnings: &mut Vec<String>,
) -> Result<(), EmitError> {
    let nets = extract_nets(sheet);
    let ports = collect_entity_ports(sheet, &nets);

    // Parameter list. BHDL entity port syntax (per the spec and
    // the `entity Res(value: resistance) { pin 1: signal inout }`
    // examples in `bhdl-stdlib/passive/`):
    //   `entity Name(...) { pin X: <kind>; ... <body>; }`
    // Ports live INSIDE the body as `pin X: <kind>;` declarations,
    // not in the parenthesised parameter list (which is for
    // generic-style entity parameters like `value: resistance`).
    writeln!(out, "entity {}() {{", entity_name)?;

    // Pin declarations for every port (hierarchical labels +
    // power/ground rails lifted from inside the sheet).
    for p in &ports {
        writeln!(out, "    pin {}: {};", p.name, p.kind)?;
    }
    if !ports.is_empty() { writeln!(out)?; }

    // No `power FOO = X V;` / `ground FOO;` decls inside the
    // entity body — those are board-only. Power references inside
    // resolve to the lifted ports above. See
    // `bhdl-parser/src/top_level.rs::parse_entity_contents`.

    emit_component_decls(out, sheet, mapping, warnings)?;
    writeln!(out)?;
    emit_net_connections(out, &nets, sheet, mapping)?;

    writeln!(out, "}}")?;
    Ok(())
}

// ──────────────────────────────────────────────────────────────
// Shared emission helpers
// ──────────────────────────────────────────────────────────────

fn emit_power_decls(out: &mut String, sheet: &Sheet, nets: &NetList) -> Result<(), EmitError> {
    // Collect power-net names that the net-extractor identified.
    // Cross-reference with PowerSymbol categories from the IR so
    // we know which ones are grounds vs supplies.
    let mut emitted: BTreeSet<String> = BTreeSet::new();
    for net in &nets.nets {
        if !net.is_power || !emitted.insert(net.name.clone()) { continue; }
        // Find a power symbol matching this net to pull its
        // category/voltage.
        let ps = sheet.power_symbols.iter().find(|p| {
            let canon = crate::nets::canonical_power_name_for_test(&p.label, p.category);
            canon == net.name
        });
        match ps {
            Some(p) if p.category == PowerCategory::Ground => {
                writeln!(out, "    ground {};", net.name)?;
            }
            Some(p) => {
                if let Some(v) = p.voltage {
                    writeln!(out, "    power {} = {}V;", net.name, format_num(v))?;
                } else {
                    writeln!(out, "    power {};", net.name)?;
                }
            }
            None => {
                writeln!(out, "    power {};", net.name)?;
            }
        }
    }
    Ok(())
}

fn emit_component_decls(
    out: &mut String,
    sheet: &Sheet,
    mapping: &MappingRegistry,
    warnings: &mut Vec<String>,
) -> Result<(), EmitError> {
    writeln!(out, "    // Components")?;
    // Multi-unit parts (resistor packs, op-amp duals, gate ICs)
    // appear as several symbol instances sharing one reference
    // designator. Emit one declaration per unique ref.
    let mut seen_refs: BTreeSet<String> = BTreeSet::new();
    for sym in &sheet.symbols {
        // Power flags are *not* component instances; their
        // contribution is the net name they bestow.
        if sym.lib_id.starts_with("power:") {
            continue;
        }
        let ref_des = sym.reference().unwrap_or("U_unknown").to_string();
        if !seen_refs.insert(ref_des) { continue; }
        let m = mapping.lookup(&sym.lib_id);
        let entity_name = match m {
            Some(m) if !m.is_power_net() => m.bhdl.as_str(),
            _ => {
                warnings.push(format!(
                    "unmapped KiCad symbol {:?} (ref={}); falling back to kicad_passthrough",
                    sym.lib_id,
                    sym.reference().unwrap_or("?"),
                ));
                "kicad_passthrough"
            }
        };
        let inst_ident = sanitise_ident(sym.reference().unwrap_or("U_unknown"));
        let value = sym.value().unwrap_or("").trim();
        // v0.2 generic-form passives: emit `Resistor<10kΩ>()` instead
        // of `Resistor("10k")`. The value moves from a string-typed
        // constructor argument to a typed-literal generic argument
        // (spec §2.1, Phase 1).
        let inst_line = if let Some(generics) = passive_generics(entity_name, value) {
            format!("    {}: {}<{}>();", inst_ident, entity_name, generics)
        } else {
            let arg = if value.is_empty() || value == sym.reference().unwrap_or("") {
                String::new()
            } else {
                format!("\"{}\"", value.replace('"', "\\\""))
            };
            format!("    {}: {}({});", inst_ident, entity_name, arg)
        };
        writeln!(out, "{}", inst_line)?;
    }
    Ok(())
}

fn emit_net_connections(
    out: &mut String,
    nets: &NetList,
    sheet: &Sheet,
    mapping: &MappingRegistry,
) -> Result<(), EmitError> {
    writeln!(out, "    // Connections")?;
    // Map symbol UUID → (reference designator, KiCad lib_id) so we
    // can translate KiCad pin numbers to BHDL port names via the
    // mapping registry's `pin_map`. Without this translation,
    // e.g. `D4.1` is emitted verbatim — but the LED entity
    // declares pins `K` and `A`, not `1` and `2`. The connection
    // then fails to bind to any pin instance.
    let mut ref_and_lib: BTreeMap<&str, (String, &str)> = BTreeMap::new();
    for sym in &sheet.symbols {
        let r = sanitise_ident(sym.reference().unwrap_or("U_unknown"));
        ref_and_lib.insert(sym.uuid.as_str(), (r, sym.lib_id.as_str()));
    }

    for net in &nets.nets {
        if net.pins.is_empty() { continue; }
        let net_ref = net_reference(net);
        for pin in &net.pins {
            let (inst, lib_id) = match ref_and_lib.get(pin.symbol_uuid.as_str()) {
                Some((r, l)) => (r.clone(), *l),
                None => ("U_unknown".to_string(), ""),
            };
            // Translate the KiCad pin number through the mapping
            // registry. For mapped components with an explicit
            // pin_map, `D4.1` → `D4.K`. For unmapped components
            // (passthroughs) or pins not in the map, the pin
            // number passes through unchanged.
            let pin_name = mapping.lookup(lib_id)
                .map(|m| m.translate_pin(&pin.pin_number).to_string())
                .unwrap_or_else(|| pin.pin_number.clone());
            writeln!(out, "    {} -> {}.{};", net_ref, inst, pin_name)?;
        }
    }
    Ok(())
}

/// Wire each subsheet instance's power/ground ports to the
/// board's matching power-rail. The subsheet emitter lifted
/// implicit power-globals to explicit ports; this emits the
/// parent-side wiring so the rails reach the inner components.
///
/// For each subsheet instance, walks the child sheet's nets, and
/// for every `is_power == true` net with at least one pin
/// connection, emits a `RAIL -> instance.RAIL;` line. The port
/// name on the entity equals the canonical power-rail name (per
/// `collect_entity_ports`), so the names line up.
fn emit_subsheet_power_wiring(
    out: &mut String,
    schematic: &Schematic,
) -> Result<(), EmitError> {
    let mut emitted_any = false;
    for sr in &schematic.root.sheet_refs {
        let Some(child) = schematic.child_sheets.get(&sr.file_path) else { continue; };
        let inst_name = sanitise_ident(&sr.name);
        let child_nets = extract_nets(child);
        for net in &child_nets.nets {
            if !net.is_power || net.pins.is_empty() { continue; }
            let port = sanitise_ident(&net.name);
            if !emitted_any {
                writeln!(out, "    // Power/ground wiring into hierarchical subsheets")?;
                emitted_any = true;
            }
            writeln!(out, "    {} -> {}.{};", net.name, inst_name, port)?;
        }
    }
    Ok(())
}

fn emit_subsheet_connections(out: &mut String, sheet: &Sheet, nets: &NetList) -> Result<(), EmitError> {
    writeln!(out, "    // Sheet-pin connections (parent ↔ subsheet ports)")?;
    for sr in &sheet.sheet_refs {
        let inst_name = sanitise_ident(&sr.name);
        for sp in &sr.pins {
            // Find which net this sheet pin sits on. The
            // net-extractor interned the sheet-pin coordinate but
            // didn't register the sheet pin as a NetPin, so we
            // recover the net by coordinate match.
            let port = sanitise_ident(&sp.name);
            let net_name = find_net_at(nets, sheet, (sp.at.0, sp.at.1))
                .map(|n| net_reference(n))
                .unwrap_or_else(|| format!("@unconnected_{}", port));
            writeln!(out, "    {} -> {}.{};", net_name, inst_name, port)?;
        }
    }
    Ok(())
}

// ──────────────────────────────────────────────────────────────
// Import emission
// ──────────────────────────────────────────────────────────────

/// Walk every symbol in the schematic and collect the BHDL
/// entity names the emitter will reference (mapped + the
/// passthrough fallback when unmapped). Skips `power:*` lib_ids
/// (those produce net decls, not entity instances).
fn collect_used_stdlib_entities(
    schematic: &Schematic,
    mapping: &MappingRegistry,
) -> BTreeSet<String> {
    let mut used: BTreeSet<String> = BTreeSet::new();
    let mut needs_passthrough = false;
    for sheet in std::iter::once(&schematic.root).chain(schematic.child_sheets.values()) {
        for sym in &sheet.symbols {
            if sym.lib_id.starts_with("power:") { continue; }
            match mapping.lookup(&sym.lib_id) {
                Some(m) if !m.is_power_net() => { used.insert(m.bhdl.clone()); }
                _ => { needs_passthrough = true; }
            }
        }
    }
    if needs_passthrough {
        used.insert("kicad_passthrough".to_string());
    }
    used
}

/// Known stdlib entity → source-file location mapping. Mirrors
/// `bhdl-stdlib/`'s directory layout.
///
/// **Discipline**: each target file MUST be parser-compatible
/// (parseable by the current `bhdl-parser`). bhdl-stdlib ships
/// two grammar tiers — the rich `passives/resistor.bhdl`
/// (`@metadata(...)`, complex type exprs — currently un-parseable)
/// and the parser-compatible `passives/resistor_simple.bhdl`
/// / `passive/resistor.bhdl` (v2.0 grammar). The importer points
/// at the latter tier so emitted BHDL round-trips through the
/// real synthesizer. When the parser/stdlib grammar gap closes,
/// flip the table back to the rich variants for richer
/// downstream analysis.
fn stdlib_entity_file(entity: &str) -> &'static str {
    match entity {
        // Passives: parser-compatible "_simple" variants (already
        // export the PascalCase names our mapping registry uses).
        "Resistor"                       => "passives/resistor_simple.bhdl",
        "Capacitor"                      => "passives/capacitor_simple.bhdl",
        "Inductor"                       => "passives/inductor_simple.bhdl",
        // Short-name aliases (`Res`, `Cap`, `Ind`) live in the v2
        // `passive/` (singular) tree — used when callers reference
        // them directly. The importer's registry currently always
        // emits the PascalCase names, so these branches are for
        // safety / future use.
        "Res"                            => "passive/resistor.bhdl",
        "Cap" | "ElectrolyticCap"        => "passive/capacitor.bhdl",
        "Ind"                            => "passive/inductor.bhdl",
        "Diode"                          => "passive/diode.bhdl",
        "LED"                            => "optoelectronic/led.bhdl",
        // Protection / specials — point at the small v2 tree where
        // a parser-compatible variant exists.
        "TVSDiode"                       => "protection/tvs.bhdl",
        // Generic pin-header family. Each entity declares 1..N
        // numeric pins matching KiCad's flat numbering.
        "Pin_Header_01x02"
            | "Pin_Header_01x03"
            | "Pin_Header_01x04"
            | "Pin_Header_01x06"
            | "Pin_Header_01x08"
            | "Pin_Header_01x10"
            | "Pin_Header_02x02"
            | "Pin_Header_02x03"
            | "Pin_Header_01x15"
            | "Pin_Header_01x17"
            | "Pin_Header_02x18"          => "connectors/pin_header.bhdl",
        "USB_C_Receptacle_USB2_16P"      => "connectors/usb_c.bhdl",
        "MOSFET"                         => "actives/mosfet_simple.bhdl",
        "ATmega328P_DIP28"
            | "ATmega328P_QFN32"          => "actives/atmega328p.bhdl",
        "ATmega32U4_TQFP44"               => "actives/atmega32u4.bhdl",
        "ATmega2560_TQFP100"              => "actives/atmega2560.bhdl",
        "LMV358"                          => "actives/lmv358.bhdl",
        "ATmega16U2_QFN32"                => "actives/atmega16u2.bhdl",
        "FT232RL"                         => "actives/ft232rl.bhdl",
        "NCP1117_Simple"                  => "power/ncp1117_simple.bhdl",
        "LP2985_Simple"                   => "power/lp2985_simple.bhdl",
        "Crystal"
            | "Crystal_GND2"
            | "Crystal_GND24"             => "passive/crystal.bhdl",
        "R_Pack04_Split"                  => "passives/resistor_pack.bhdl",
        "SW_Push"
            | "SW_Tactile_4Pad"           => "electromechanical/switch.bhdl",
        "Varistor"                        => "passive/varistor.bhdl",
        "Barrel_Jack_Switch"              => "connectors/barrel_jack.bhdl",
        "SolderJumper_2_Open"             => "passive/solder_jumper.bhdl",
        "Bead"
            | "Fuse"                      => "passive/inline_passives.bhdl",
        "Fiducial"                        => "mechanical/fiducial.bhdl",
        // No parser-compatible Bead / Fuse / TestPoint / Schottky /
        // BJT / MOSFET yet — they live only in the rich tier.
        // Fall back to passthrough so the import line still
        // resolves cleanly. (The instance will fail synthesis with
        // a clear "no pins on kicad_passthrough" message — easier
        // to diagnose than a 100-line parse-error dump.)
        "kicad_passthrough"              => "kicad_passthrough.bhdl",
        _                                => "kicad_passthrough.bhdl",
    }
}

/// Group entities by source file (so we get one `import { A, B }
/// from "..."` per file), then write the import block.
fn emit_imports(
    out: &mut String,
    stdlib_path: &std::path::Path,
    entities: &BTreeSet<String>,
) -> Result<(), EmitError> {
    let mut by_file: BTreeMap<&'static str, Vec<&str>> = BTreeMap::new();
    for ent in entities {
        let file = stdlib_entity_file(ent);
        by_file.entry(file).or_default().push(ent.as_str());
    }
    for (file, ents) in by_file {
        let full = stdlib_path.join(file);
        // BHDL's import statement uses `{ A, B } from "path";`
        // shape — see `bhdl-stdlib/basic_components.bhdl` for
        // canonical examples.
        let names = ents.join(", ");
        writeln!(out, "import {{ {} }} from \"{}\";", names, full.display())?;
    }
    Ok(())
}

// ──────────────────────────────────────────────────────────────
// Naming helpers
// ──────────────────────────────────────────────────────────────

/// How to reference a net in connection lines. Power nets use
/// the bare name; local nets get an `@` prefix.
///
/// Net names are sanitised because KiCad permits punctuation in
/// label text (e.g. `RD+` for a USB differential-pair high
/// signal) that BHDL's lexer rejects as identifier characters.
/// `sanitise_ident` maps `+` / `-` / `/` etc. to `_`, matching
/// how labels themselves are sanitised at the point of net
/// naming. Without this fix, an Arduino UNO emit produces
/// `@RD+ -> R1.1;` which the parser bails on at the `+`.
fn net_reference(net: &Net) -> String {
    let safe = sanitise_ident(&net.name);
    if net.is_power { safe } else { format!("@{}", safe) }
}

/// Map a child sheet's on-disk path to a BHDL entity name.
fn sheet_entity_name(path: &std::path::Path) -> String {
    let stem = path.file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("subsheet");
    sanitise_ident(stem)
}

/// Sanitise a raw KiCad string (reference, sheet name, port name)
/// to a valid BHDL identifier. Replaces non-alnum chars with `_`,
/// prefixes with `_` if the first char is a digit.
fn sanitise_ident(raw: &str) -> String {
    if raw.is_empty() { return "_".to_string(); }
    // Polarity-preserving substitutions for diff-pair / differential-
    // signal labels. KiCad commonly names differential pairs `D+` /
    // `D-`, `RD+` / `RD-`, `TX+` / `TX-`. A naive `+`/`-` → `_`
    // collapse merges those into a single identifier, which produces
    // wrong netlists (the `+` and `-` signals get conflated). Keep
    // them distinct: `+` → `_P`, `-` → `_N`. Other punctuation still
    // becomes `_`.
    let mut out = String::with_capacity(raw.len() + 2);
    for c in raw.chars() {
        if c.is_ascii_alphanumeric() || c == '_' {
            out.push(c);
        } else if c == '+' {
            out.push_str("_P");
        } else if c == '-' {
            out.push_str("_N");
        } else {
            out.push('_');
        }
    }
    if out.chars().next().map_or(true, |c| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    out
}

/// Format a floating-point voltage compactly: integers as integer,
/// fractions to up to 3 decimal places.
fn format_num(v: f64) -> String {
    if (v - v.round()).abs() < 1e-6 {
        format!("{}", v.round() as i64)
    } else {
        let s = format!("{:.3}", v);
        // Trim trailing zeroes from the fractional part.
        let s = s.trim_end_matches('0').trim_end_matches('.');
        s.to_string()
    }
}

/// Translate a KiCad value string into a typed-literal generic
/// argument for a v0.2 generic passive (Resistor, Capacitor,
/// Inductor). Returns `Some(literal)` when `entity` is a generic
/// passive *and* `value` parses cleanly; returns `None` otherwise,
/// signalling to the caller that the legacy
/// `Entity("string")` form should be used.
///
/// Examples:
///
///     passive_generics("Resistor", "10k")    -> Some("10kΩ")
///     passive_generics("Resistor", "1M")     -> Some("1MΩ")
///     passive_generics("Capacitor", "100nF") -> Some("100nF")
///     passive_generics("Capacitor", "22uF")  -> Some("22µF")
///     passive_generics("Inductor", "10uH")   -> Some("10µH")
///     passive_generics("ATmega328P_DIP28", _) -> None  // not a passive
///     passive_generics("Resistor", "")       -> None  // no value
///
/// The output is what BHDL's parser accepts in a generic-arg
/// position — number + SI prefix + unit suffix. SI µ is normalised
/// from KiCad's common `u` shorthand.
fn passive_generics(entity: &str, value: &str) -> Option<String> {
    let unit = match entity {
        "Resistor" => "Ω",
        "Capacitor" => "F",
        "Inductor"  => "H",
        _ => return None,
    };
    let v = value.trim();
    if v.is_empty() { return None; }

    // Strip an existing unit suffix matching this entity's unit. We
    // accept the SI symbol (Ω/F/H) verbatim or KiCad's common
    // ASCII fallback ("R" for Ω on resistors, plain "F"/"H").
    let stripped = v
        .strip_suffix(unit)
        .or_else(|| if unit == "Ω" { v.strip_suffix('R').or_else(|| v.strip_suffix('Ω')) } else { None })
        .unwrap_or(v);

    // Split into (number, prefix). The SI prefix can be at the very
    // end of the stripped string ('k', 'K', 'M', 'm', 'u', 'µ',
    // 'n', 'p'). KiCad commonly uses 'k' or 'K' for kilo and 'u'
    // for micro; normalise.
    let (num_part, si_prefix) = if let Some(last) = stripped.chars().last() {
        match last {
            'k' | 'K' => (stripped[..stripped.len() - last.len_utf8()].to_string(), "k"),
            'M'       => (stripped[..stripped.len() - 1].to_string(), "M"),
            'm'       => (stripped[..stripped.len() - 1].to_string(), "m"),
            'u' | 'µ' => (stripped[..stripped.len() - last.len_utf8()].to_string(), "µ"),
            'n'       => (stripped[..stripped.len() - 1].to_string(), "n"),
            'p'       => (stripped[..stripped.len() - 1].to_string(), "p"),
            _         => (stripped.to_string(), ""),
        }
    } else {
        return None;
    };

    // The remaining number part must parse as a positive float
    // (with optional decimal point). Reject everything else.
    if num_part.is_empty() { return None; }
    if num_part.parse::<f64>().is_err() { return None; }

    Some(format!("{}{}{}", num_part, si_prefix, unit))
}

/// Look up which net a coordinate lands on. Used for sheet-pin →
/// net resolution. Linear search through `nets.nets[*].pins` is
/// too coarse (pins record symbol UUID, not coordinate), so we go
/// through the sheet's pin_positions and find the matching pin.
fn find_net_at<'a>(nets: &'a NetList, sheet: &Sheet, at: (f64, f64)) -> Option<&'a Net> {
    // Find a pin position close to `at`; then locate the net it
    // belongs to via symbol_uuid + pin_number.
    const EPS: f64 = 0.01; // 10 µm
    for sym in &sheet.symbols {
        for pp in &sym.pin_positions {
            if (pp.at.0 - at.0).abs() < EPS && (pp.at.1 - at.1).abs() < EPS {
                return nets.nets.iter().find(|n| n.pins.iter()
                    .any(|p| p.symbol_uuid == sym.uuid && p.pin_number == pp.pin_number));
            }
        }
    }
    // Fallback: sheet pins sit at the edge of the subsheet symbol;
    // a wire from the parent ought to terminate exactly there. We
    // don't have a pin record at that exact spot, so we can't
    // resolve the net deterministically — caller will use the
    // unconnected stub.
    None
}
