//! BHDL emitter.
//!
//! Phase D of the KiCad-to-BHDL translator (plan §5.4). Consumes
//! a parsed [`Schematic`], the per-sheet [`NetList`]s produced by
//! [`crate::nets::extract_nets`], and the
//! [`crate::symbol_mapping::MappingRegistry`], and produces a
//! `.bhdl` source string.
//!
//! ## Hierarchy
//!
//! The root sheet emits a top-level `board` block. Each child
//! sheet emits an `entity` block alongside, with the child's
//! hierarchical labels surfaced as ports. The board block
//! instantiates each subsheet exactly where it appeared in the
//! parent — one entity instance per `(sheet ...)` reference, so
//! reused sub-circuits collapse naturally to multiple instances of
//! the same entity.
//!
//! ## Power and globals
//!
//! Power-flag symbols (`+5V`, `GND`, …) become `power NAME = …;`
//! / `ground NAME;` declarations on the board, and references to
//! them in pin connections use the bare name (no `@` prefix).
//! Local nets get an `@` prefix; unnamed local nets are emitted as
//! `@Net_<n>`.
//!
//! ## Unmapped symbols
//!
//! KiCad lib_ids that aren't in the mapping registry fall through
//! to the `kicad_passthrough` entity — a placeholder that carries
//! the KiCad reference designator + value + footprint as
//! attributes so the import never aborts on an unknown part. The
//! "enrich" phase upgrades these to real stdlib entries one
//! library at a time.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

use crate::ir::{PowerCategory, Sheet, Schematic};
use crate::nets::{extract_nets, Net, NetList};
use crate::symbol_mapping::MappingRegistry;

/// Errors specific to BHDL emission.
#[derive(Debug, thiserror::Error)]
pub enum EmitError {
    #[error("formatting error: {0}")]
    Fmt(#[from] std::fmt::Error),
}

/// Output of the emitter — one BHDL source string covering the
/// whole schematic (board + nested entity definitions).
pub struct EmittedBhdl {
    pub board_name: String,
    pub source: String,
    /// Diagnostics gathered during emission. Non-fatal: each one
    /// names a symbol or net that the importer couldn't fully
    /// resolve, so reviewers know what to enrich.
    pub warnings: Vec<String>,
}

/// Emission options. Use `EmitOptions::default()` for the
/// behaviour the older `emit_bhdl(...)` function had; set
/// `stdlib_path` when the emitted BHDL needs to compile through
/// `bhdl-synthesizer` (round-trip tests, real-world use).
#[derive(Debug, Clone, Default)]
pub struct EmitOptions {
    /// Path to `bhdl-stdlib/` on disk. When set, the emitter
    /// prepends `import { ... } from "<stdlib_path>/<rel>.bhdl";`
    /// lines for every stdlib entity referenced. When None, no
    /// import header is emitted (older callers, tests that
    /// don't care about parser-validity).
    pub stdlib_path: Option<std::path::PathBuf>,
}

/// Backwards-compatible entry point. Delegates to
/// `emit_bhdl_with_options(...)` with default options (no
/// imports emitted).
pub fn emit_bhdl(
    schematic: &Schematic,
    mapping: &MappingRegistry,
    board_name: &str,
) -> Result<EmittedBhdl, EmitError> {
    emit_bhdl_with_options(schematic, mapping, board_name, &EmitOptions::default())
}

/// Main entry point. `board_name` is the identifier used for the
/// top-level `board` block (typically the .kicad_sch filename
/// without extension, but the caller decides). `opts` carries
/// optional configuration like the stdlib search path for
/// import generation.
pub fn emit_bhdl_with_options(
    schematic: &Schematic,
    mapping: &MappingRegistry,
    board_name: &str,
    opts: &EmitOptions,
) -> Result<EmittedBhdl, EmitError> {
    let mut out = String::new();
    let mut warnings = Vec::new();
    let board_ident = sanitise_ident(board_name);

    // ── header ────────────────────────────────────────────────
    writeln!(out, "// Auto-generated by bhdl-kicad-import from {}.",
        schematic.root.path.display())?;
    writeln!(out, "// KiCad generator: {} (format version {})",
        schematic.generator, schematic.version)?;
    writeln!(out, "// Edit freely — re-running the importer will preserve user changes")?;
    writeln!(out, "// only if you keep the section markers intact.")?;
    writeln!(out)?;

    // ── imports ───────────────────────────────────────────────
    if let Some(stdlib_path) = &opts.stdlib_path {
        let used = collect_used_stdlib_entities(schematic, mapping);
        emit_imports(&mut out, stdlib_path, &used)?;
        writeln!(out)?;
    }

    // ── child sheets first (so they're defined before use) ────
    // Stable iteration order: BTreeMap of sheet path → Sheet.
    let mut child_sheets: BTreeMap<&std::path::Path, &Sheet> = BTreeMap::new();
    for (path, sheet) in &schematic.child_sheets {
        child_sheets.insert(path.as_path(), sheet);
    }
    for (path, sheet) in &child_sheets {
        let ent_name = sheet_entity_name(path);
        emit_subsheet_entity(&mut out, &ent_name, sheet, mapping, &mut warnings)?;
        writeln!(out)?;
    }

    // ── top-level board ───────────────────────────────────────
    emit_board(&mut out, &board_ident, schematic, mapping, &mut warnings)?;

    Ok(EmittedBhdl { board_name: board_ident, source: out, warnings })
}

// ──────────────────────────────────────────────────────────────
// Board emission
// ──────────────────────────────────────────────────────────────

fn emit_board(
    out: &mut String,
    board_ident: &str,
    schematic: &Schematic,
    mapping: &MappingRegistry,
    warnings: &mut Vec<String>,
) -> Result<(), EmitError> {
    let sheet = &schematic.root;
    let nets = extract_nets(sheet);

    writeln!(out, "board {} {{", board_ident)?;

    // Power & ground declarations (one per distinct power-net name).
    emit_power_decls(out, sheet, &nets)?;
    writeln!(out)?;

    // Component instances.
    emit_component_decls(out, sheet, mapping, warnings)?;
    writeln!(out)?;

    // Subsheet instances.
    if !schematic.child_sheets.is_empty() {
        writeln!(out, "    // Hierarchical subsheets")?;
        for sr in &sheet.sheet_refs {
            let ent_name = sheet_entity_name(&sr.file_path);
            let inst_name = sanitise_ident(&sr.name);
            writeln!(out, "    {}: {}();", inst_name, ent_name)?;
        }
        writeln!(out)?;
        // Connections from the parent into each subsheet's ports
        // (one per sheet pin → net mapping).
        emit_subsheet_connections(out, sheet, &nets)?;
        writeln!(out)?;
    }

    // Net connections.
    emit_net_connections(out, &nets, sheet)?;

    writeln!(out, "}}")?;
    Ok(())
}

// ──────────────────────────────────────────────────────────────
// Subsheet (entity) emission
// ──────────────────────────────────────────────────────────────

fn emit_subsheet_entity(
    out: &mut String,
    entity_name: &str,
    sheet: &Sheet,
    mapping: &MappingRegistry,
    warnings: &mut Vec<String>,
) -> Result<(), EmitError> {
    let nets = extract_nets(sheet);

    // Ports come from hierarchical labels — these are the
    // schematic's stated interface to the parent.
    let mut port_names: BTreeSet<String> = BTreeSet::new();
    for hl in &sheet.hierarchical_labels {
        port_names.insert(sanitise_ident(&hl.text));
    }

    write!(out, "entity {}(", entity_name)?;
    let mut first = true;
    for p in &port_names {
        if !first { write!(out, ", ")?; }
        write!(out, "{}: signal inout", p)?;
        first = false;
    }
    writeln!(out, ") {{")?;

    // Power decls (still local to the subsheet — power flags in a
    // child sheet are conceptually local power references that
    // happen to share a name with the parent's rails).
    emit_power_decls(out, sheet, &nets)?;
    writeln!(out)?;

    emit_component_decls(out, sheet, mapping, warnings)?;
    writeln!(out)?;
    emit_net_connections(out, &nets, sheet)?;

    writeln!(out, "}}")?;
    Ok(())
}

// ──────────────────────────────────────────────────────────────
// Shared emission helpers
// ──────────────────────────────────────────────────────────────

fn emit_power_decls(out: &mut String, sheet: &Sheet, nets: &NetList) -> Result<(), EmitError> {
    // Collect power-net names that the net-extractor identified.
    // Cross-reference with PowerSymbol categories from the IR so
    // we know which ones are grounds vs supplies.
    let mut emitted: BTreeSet<String> = BTreeSet::new();
    for net in &nets.nets {
        if !net.is_power || !emitted.insert(net.name.clone()) { continue; }
        // Find a power symbol matching this net to pull its
        // category/voltage.
        let ps = sheet.power_symbols.iter().find(|p| {
            let canon = crate::nets::canonical_power_name_for_test(&p.label, p.category);
            canon == net.name
        });
        match ps {
            Some(p) if p.category == PowerCategory::Ground => {
                writeln!(out, "    ground {};", net.name)?;
            }
            Some(p) => {
                if let Some(v) = p.voltage {
                    writeln!(out, "    power {} = {}V;", net.name, format_num(v))?;
                } else {
                    writeln!(out, "    power {};", net.name)?;
                }
            }
            None => {
                writeln!(out, "    power {};", net.name)?;
            }
        }
    }
    Ok(())
}

fn emit_component_decls(
    out: &mut String,
    sheet: &Sheet,
    mapping: &MappingRegistry,
    warnings: &mut Vec<String>,
) -> Result<(), EmitError> {
    writeln!(out, "    // Components")?;
    // Multi-unit parts (resistor packs, op-amp duals, gate ICs)
    // appear as several symbol instances sharing one reference
    // designator. Emit one declaration per unique ref.
    let mut seen_refs: BTreeSet<String> = BTreeSet::new();
    for sym in &sheet.symbols {
        // Power flags are *not* component instances; their
        // contribution is the net name they bestow.
        if sym.lib_id.starts_with("power:") {
            continue;
        }
        let ref_des = sym.reference().unwrap_or("U_unknown").to_string();
        if !seen_refs.insert(ref_des) { continue; }
        let m = mapping.lookup(&sym.lib_id);
        let entity_name = match m {
            Some(m) if !m.is_power_net() => m.bhdl.as_str(),
            _ => {
                warnings.push(format!(
                    "unmapped KiCad symbol {:?} (ref={}); falling back to kicad_passthrough",
                    sym.lib_id,
                    sym.reference().unwrap_or("?"),
                ));
                "kicad_passthrough"
            }
        };
        let inst_ident = sanitise_ident(sym.reference().unwrap_or("U_unknown"));
        let value = sym.value().unwrap_or("").trim();
        let arg = if value.is_empty() || value == sym.reference().unwrap_or("") {
            String::new()
        } else {
            format!("\"{}\"", value.replace('"', "\\\""))
        };
        writeln!(out, "    {}: {}({});", inst_ident, entity_name, arg)?;
    }
    Ok(())
}

fn emit_net_connections(out: &mut String, nets: &NetList, sheet: &Sheet) -> Result<(), EmitError> {
    writeln!(out, "    // Connections")?;
    // Map symbol UUID → reference designator (for emit).
    let mut ref_of: BTreeMap<&str, String> = BTreeMap::new();
    for sym in &sheet.symbols {
        let r = sanitise_ident(sym.reference().unwrap_or("U_unknown"));
        ref_of.insert(sym.uuid.as_str(), r);
    }

    for net in &nets.nets {
        if net.pins.is_empty() { continue; }
        let net_ref = net_reference(net);
        for pin in &net.pins {
            let inst = ref_of.get(pin.symbol_uuid.as_str())
                .cloned()
                .unwrap_or_else(|| "U_unknown".into());
            writeln!(out, "    {} -> {}.{};", net_ref, inst, pin.pin_number)?;
        }
    }
    Ok(())
}

fn emit_subsheet_connections(out: &mut String, sheet: &Sheet, nets: &NetList) -> Result<(), EmitError> {
    writeln!(out, "    // Sheet-pin connections (parent ↔ subsheet ports)")?;
    for sr in &sheet.sheet_refs {
        let inst_name = sanitise_ident(&sr.name);
        for sp in &sr.pins {
            // Find which net this sheet pin sits on. The
            // net-extractor interned the sheet-pin coordinate but
            // didn't register the sheet pin as a NetPin, so we
            // recover the net by coordinate match.
            let port = sanitise_ident(&sp.name);
            let net_name = find_net_at(nets, sheet, (sp.at.0, sp.at.1))
                .map(|n| net_reference(n))
                .unwrap_or_else(|| format!("@unconnected_{}", port));
            writeln!(out, "    {} -> {}.{};", net_name, inst_name, port)?;
        }
    }
    Ok(())
}

// ──────────────────────────────────────────────────────────────
// Import emission
// ──────────────────────────────────────────────────────────────

/// Walk every symbol in the schematic and collect the BHDL
/// entity names the emitter will reference (mapped + the
/// passthrough fallback when unmapped). Skips `power:*` lib_ids
/// (those produce net decls, not entity instances).
fn collect_used_stdlib_entities(
    schematic: &Schematic,
    mapping: &MappingRegistry,
) -> BTreeSet<String> {
    let mut used: BTreeSet<String> = BTreeSet::new();
    let mut needs_passthrough = false;
    for sheet in std::iter::once(&schematic.root).chain(schematic.child_sheets.values()) {
        for sym in &sheet.symbols {
            if sym.lib_id.starts_with("power:") { continue; }
            match mapping.lookup(&sym.lib_id) {
                Some(m) if !m.is_power_net() => { used.insert(m.bhdl.clone()); }
                _ => { needs_passthrough = true; }
            }
        }
    }
    if needs_passthrough {
        used.insert("kicad_passthrough".to_string());
    }
    used
}

/// Known stdlib entity → source-file location mapping. Mirrors
/// `bhdl-stdlib/`'s directory layout.
///
/// **Discipline**: each target file MUST be parser-compatible
/// (parseable by the current `bhdl-parser`). bhdl-stdlib ships
/// two grammar tiers — the rich `passives/resistor.bhdl`
/// (`@metadata(...)`, complex type exprs — currently un-parseable)
/// and the parser-compatible `passives/resistor_simple.bhdl`
/// / `passive/resistor.bhdl` (v2.0 grammar). The importer points
/// at the latter tier so emitted BHDL round-trips through the
/// real synthesizer. When the parser/stdlib grammar gap closes,
/// flip the table back to the rich variants for richer
/// downstream analysis.
fn stdlib_entity_file(entity: &str) -> &'static str {
    match entity {
        // Passives: parser-compatible "_simple" variants (already
        // export the PascalCase names our mapping registry uses).
        "Resistor"                       => "passives/resistor_simple.bhdl",
        "Capacitor"                      => "passives/capacitor_simple.bhdl",
        "Inductor"                       => "passives/inductor_simple.bhdl",
        // Short-name aliases (`Res`, `Cap`, `Ind`) live in the v2
        // `passive/` (singular) tree — used when callers reference
        // them directly. The importer's registry currently always
        // emits the PascalCase names, so these branches are for
        // safety / future use.
        "Res"                            => "passive/resistor.bhdl",
        "Cap" | "ElectrolyticCap"        => "passive/capacitor.bhdl",
        "Ind"                            => "passive/inductor.bhdl",
        "Diode"                          => "passive/diode.bhdl",
        "LED"                            => "optoelectronic/led.bhdl",
        // Protection / specials — point at the small v2 tree where
        // a parser-compatible variant exists.
        "TVSDiode"                       => "protection/tvs.bhdl",
        // No parser-compatible Bead / Fuse / TestPoint / Schottky /
        // BJT / MOSFET yet — they live only in the rich tier.
        // Fall back to passthrough so the import line still
        // resolves cleanly. (The instance will fail synthesis with
        // a clear "no pins on kicad_passthrough" message — easier
        // to diagnose than a 100-line parse-error dump.)
        "kicad_passthrough"              => "kicad_passthrough.bhdl",
        _                                => "kicad_passthrough.bhdl",
    }
}

/// Group entities by source file (so we get one `import { A, B }
/// from "..."` per file), then write the import block.
fn emit_imports(
    out: &mut String,
    stdlib_path: &std::path::Path,
    entities: &BTreeSet<String>,
) -> Result<(), EmitError> {
    let mut by_file: BTreeMap<&'static str, Vec<&str>> = BTreeMap::new();
    for ent in entities {
        let file = stdlib_entity_file(ent);
        by_file.entry(file).or_default().push(ent.as_str());
    }
    for (file, ents) in by_file {
        let full = stdlib_path.join(file);
        // BHDL's import statement uses `{ A, B } from "path";`
        // shape — see `bhdl-stdlib/basic_components.bhdl` for
        // canonical examples.
        let names = ents.join(", ");
        writeln!(out, "import {{ {} }} from \"{}\";", names, full.display())?;
    }
    Ok(())
}

// ──────────────────────────────────────────────────────────────
// Naming helpers
// ──────────────────────────────────────────────────────────────

/// How to reference a net in connection lines. Power nets use
/// the bare name; local nets get an `@` prefix.
fn net_reference(net: &Net) -> String {
    if net.is_power { net.name.clone() } else { format!("@{}", net.name) }
}

/// Map a child sheet's on-disk path to a BHDL entity name.
fn sheet_entity_name(path: &std::path::Path) -> String {
    let stem = path.file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("subsheet");
    sanitise_ident(stem)
}

/// Sanitise a raw KiCad string (reference, sheet name, port name)
/// to a valid BHDL identifier. Replaces non-alnum chars with `_`,
/// prefixes with `_` if the first char is a digit.
fn sanitise_ident(raw: &str) -> String {
    if raw.is_empty() { return "_".to_string(); }
    let mut out: String = raw.chars().map(|c| {
        if c.is_ascii_alphanumeric() || c == '_' { c } else { '_' }
    }).collect();
    if out.chars().next().unwrap().is_ascii_digit() {
        out.insert(0, '_');
    }
    out
}

/// Format a floating-point voltage compactly: integers as integer,
/// fractions to up to 3 decimal places.
fn format_num(v: f64) -> String {
    if (v - v.round()).abs() < 1e-6 {
        format!("{}", v.round() as i64)
    } else {
        let s = format!("{:.3}", v);
        // Trim trailing zeroes from the fractional part.
        let s = s.trim_end_matches('0').trim_end_matches('.');
        s.to_string()
    }
}

/// Look up which net a coordinate lands on. Used for sheet-pin →
/// net resolution. Linear search through `nets.nets[*].pins` is
/// too coarse (pins record symbol UUID, not coordinate), so we go
/// through the sheet's pin_positions and find the matching pin.
fn find_net_at<'a>(nets: &'a NetList, sheet: &Sheet, at: (f64, f64)) -> Option<&'a Net> {
    // Find a pin position close to `at`; then locate the net it
    // belongs to via symbol_uuid + pin_number.
    const EPS: f64 = 0.01; // 10 µm
    for sym in &sheet.symbols {
        for pp in &sym.pin_positions {
            if (pp.at.0 - at.0).abs() < EPS && (pp.at.1 - at.1).abs() < EPS {
                return nets.nets.iter().find(|n| n.pins.iter()
                    .any(|p| p.symbol_uuid == sym.uuid && p.pin_number == pp.pin_number));
            }
        }
    }
    // Fallback: sheet pins sit at the edge of the subsheet symbol;
    // a wire from the parent ought to terminate exactly there. We
    // don't have a pin record at that exact spot, so we can't
    // resolve the net deterministically — caller will use the
    // unconnected stub.
    None
}
