//! Domain interface converters for mixed-signal simulation
//! 
//! This module provides converters that enable signal translation between
//! analog and digital simulation domains.

mod adc;
mod dac;
mod synchronizer;

pub use adc::{ADConverter, ADCConfig};
pub use dac::{DAConverter, DACConfig, AnalogUpdate};
pub use synchronizer::{DomainSynchronizer, SyncResult, SyncType};

use bhdl_netlist::NetId;
use crate::circuit::state::LogicLevel;

/// Digital event generated by A/D conversion
#[derive(Debug, Clone, PartialEq)]
pub struct DigitalEvent {
    /// Time when the event occurs (includes propagation delay)
    pub time: f64,
    /// Net that changes value
    pub net: NetId,
    /// New logic value
    pub new_value: LogicLevel,
    /// Drive strength of the converter output
    pub driver_strength: DriveStrength,
}

/// Drive strength for digital outputs
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum DriveStrength {
    /// Weak drive (high impedance)
    Weak,
    /// Standard drive strength
    Strong,
    /// High current drive
    VeryStrong,
}

/// Common interface for domain converters
pub trait DomainConverter {
    /// Get the input net(s) for this converter
    fn input_nets(&self) -> Vec<NetId>;
    
    /// Get the output net(s) for this converter
    fn output_nets(&self) -> Vec<NetId>;
    
    /// Reset converter to initial state
    fn reset(&mut self);
    
    /// Get converter statistics
    fn get_stats(&self) -> ConverterStats;
}

/// Statistics for converter operation
#[derive(Debug, Default)]
pub struct ConverterStats {
    /// Total number of conversions
    pub conversions: usize,
    /// Number of metastable events (A/D only)
    pub metastable_events: usize,
    /// Average conversion delay
    pub avg_delay: f64,
    /// Maximum observed slew rate (D/A only)
    pub max_slew_rate: Option<f64>,
}