// Re-export AST types
pub mod ast;
pub use bhdl_ast::*; // Use the AST types from the bhdl-ast crate directly

// Import parser building functions
// REMOVED: use ast::build_ast;
pub use ast::ParseError;

use tree_sitter::{Parser, Tree, Point, Language, Node};

// Declare the external C function generated by tree-sitter
extern "C" {
    fn tree_sitter_bhdl() -> Language;
}

// Placeholder for main parsing function using tree-sitter runtime
// This will need to be implemented later.
pub type ParseResult<T> = Result<T, String>; // Simple error for now

pub fn parse_bhdl_string(input: &str) -> Result<SourceFile, ParseError> {
    let mut parser = Parser::new();

    // Set the language for the parser using the external C function
    // This requires linking the grammar library correctly.
    let language = unsafe { tree_sitter_bhdl() }; // Call the C function
    parser.set_language(&language) // Use a reference to the retrieved Language struct
        .map_err(|e| ParseError::new_at_span(format!("Internal Error: Failed to set language: {}", e), 
                                             bhdl_ast::Span{ start_byte: 0, end_byte: 0, start_point: Point::default(), end_point: Point::default() }))?;

    // Parse the input string
    let tree: Option<Tree> = parser.parse(input, None);

    match tree {
        Some(t) => {
            let root_node = t.root_node();
            // Remove shared cursor declaration
            // let mut cursor = t.walk(); 

            // Check for syntax errors reported by tree-sitter
            if root_node.has_error() {
                // Find the first error node for a basic error message
                // Pass root_node directly, let the function handle cursor
                let error_span = {
                    let error_node = find_first_error_node(root_node); // Pass Node
                    error_node.map(ast::get_span).unwrap_or_else(|| 
                        bhdl_ast::Span { start_byte: 0, end_byte: input.len(), start_point: Point::default(), end_point: Point::default() } 
                    )
                };
                 return Err(ParseError::new_at_span("Syntax error detected by tree-sitter".to_string(), error_span));
            }

            // Build our custom AST from the tree-sitter tree
            // No need to reset a shared cursor
            ast::build_ast(root_node, input)
        }
        None => Err(ParseError::new_at_span("Tree-sitter failed to parse the input.".to_string(), 
                                         bhdl_ast::Span{ start_byte: 0, end_byte: input.len(), start_point: Point::default(), end_point: Point::default() })), 
    }
}

/// Helper to find the first node marked as an error by tree-sitter
// Modify signature to accept Node instead of &mut TreeCursor
fn find_first_error_node(node: Node) -> Option<Node> { 
    let mut cursor = node.walk(); // Create internal cursor
    loop {
        let current_node = cursor.node(); // Use internal cursor
        if current_node.has_error() {
            // Found an error node, try to find the specific ERROR or MISSING node within it
             if current_node.is_error() || current_node.is_missing() {
                 return Some(current_node);
             }
             // If the current node has an error but isn't the error node itself,
             // descend to find the actual error.
             if cursor.goto_first_child() {
                 continue;
             }
        }

        // Move to next sibling or parent's sibling
        if cursor.goto_next_sibling() {
            continue;
        }

        // Move up and try next sibling
        if !cursor.goto_parent() {
            break; // Reached root or failed to move up
        }
        while !cursor.goto_next_sibling() {
            if !cursor.goto_parent() {
                return None; // Back to root
            }
        }
    }
    None
}

// Keep tests module, but it will need to be rewritten
// to use the tree-sitter based parse function and AST.
#[cfg(test)]
mod tests {
    use super::*; // Import items from parent module (lib.rs)
    use tree_sitter::Point; // Import Point for dummy span

    // Helper for creating dummy spans in tests
    fn dummy_span() -> Span {
        Span { start_byte: 0, end_byte: 0, start_point: Point::new(0, 0), end_point: Point::new(0, 0) }
    }

    #[test]
    fn test_simple_board_parsing() {
        let input = r#"
        board MyBoard {
            parameters {
                PARAM1: integer = 10;
            }
            ports {
                CLK: in signal;
                RESET: in signal;
                DATA_OUT: out signal [7:0];
            }
            components {
                Resistor R1 { value = 1kOhm; };
                Capacitor C1(10uF, 16Vdc);
            }
            connections {
                CLK -> R1.1;
                R1.2 -> C1.1;
                C1.2 -> GND;
                NetA -> R1.p2; // Example using alternate pin name
            }
        }
        "#;

        let result = parse_bhdl_string(input);

        // Basic check: Ensure parsing was successful
        assert!(result.is_ok(), "Parsing failed: {:?}", result.err());

        let source_file = result.unwrap();

        // Check number of top-level items (should be 1 board definition)
        assert_eq!(source_file.items.len(), 1, "Expected 1 top-level item");

        // Check the board definition
        if let Some(TopLevelItem::BoardDefinition(board)) = source_file.items.get(0) {
            assert_eq!(board.name.name, "MyBoard");

            // --- Check Parameters Block ---
            let params_block = board.body.iter().find_map(|item| match item {
                BoardItem::ParametersBlock(pb) => Some(pb),
                _ => None,
            }).expect("Parameters block not found");
            assert_eq!(params_block.parameters.len(), 1);
            let param1 = &params_block.parameters[0];
            assert_eq!(param1.name.name, "PARAM1");
            // Check parameter type
            assert!(param1.param_type.is_some(), "PARAM1 should have a type");
            assert_eq!(param1.param_type.as_ref().unwrap().name, "integer");
            // Check parameter value
            match &param1.value {
                Expression::IntegerLiteral(lit) => assert_eq!(lit.value_text, "10"),
                _ => panic!("Expected IntegerLiteral for PARAM1 value"),
            }

            // --- Check Ports Block ---
            let ports_block = board.body.iter().find_map(|item| match item {
                BoardItem::PortsBlock(pb) => Some(pb),
                _ => None,
            }).expect("Ports block not found");
            assert_eq!(ports_block.ports.len(), 3);

            let port_clk = &ports_block.ports[0];
            assert_eq!(port_clk.name.name, "CLK");
            assert!(!port_clk.is_port); // It's a pin, not explicitly declared as port
            match &port_clk.kind {
                PinPortKind::SignalPower { direction, base_type, subtype, .. } => {
                    assert_eq!(*direction, PinDirection::In);
                    assert_eq!(*base_type, PinBaseType::Signal);
                    assert!(subtype.is_none()); // CLK: in signal; (no subtype)
                }
                _ => panic!("Incorrect kind for CLK port"),
            }

            let port_data = &ports_block.ports[2];
            assert_eq!(port_data.name.name, "DATA_OUT");
            assert!(port_data.is_port); // It's explicitly declared as port
            match &port_data.kind {
                PinPortKind::SignalPower { direction, base_type, subtype, .. } => {
                    assert_eq!(*direction, PinDirection::Out);
                    assert_eq!(*base_type, PinBaseType::Signal);
                     assert!(subtype.is_none()); // DATA_OUT: out signal [7:0]; (no subtype)
                }
                _ => panic!("Incorrect kind for DATA_OUT port"),
            }
            // Check bus specifier details
            assert!(port_data.bus_specifier.is_some(), "DATA_OUT should have bus specifier");
            let bus_spec = port_data.bus_specifier.as_ref().unwrap();
            match &bus_spec.high {
                Expression::IntegerLiteral(lit) => assert_eq!(lit.value_text, "7"),
                _ => panic!("Expected IntegerLiteral for bus specifier high bound"),
            }
            assert!(bus_spec.low.is_some(), "Bus specifier should have low bound");
            match bus_spec.low.as_ref().unwrap() {
                 Expression::IntegerLiteral(lit) => assert_eq!(lit.value_text, "0"),
                 _ => panic!("Expected IntegerLiteral for bus specifier low bound"),
            }

            // --- Check Components Block ---
            let components_block = board.body.iter().find_map(|item| match item {
                BoardItem::ComponentsBlock(cb) => Some(cb),
                _ => None,
            }).expect("Components block not found");
            assert_eq!(components_block.instantiations.len(), 2);

            let comp_r1 = &components_block.instantiations[0];
            assert_eq!(comp_r1.instance_name.name, "R1");
            assert_eq!(comp_r1.component_type.name, "Resistor");
            assert!(comp_r1.parameters.is_some());
            match comp_r1.parameters.as_ref().unwrap() {
                ComponentParameters::Named(assignments) => {
                    assert_eq!(assignments.len(), 1);
                    let assign = &assignments[0];
                    assert_eq!(assign.name.name, "value");
                    match &assign.value {
                        Expression::PhysicalLiteral(lit) => {
                             assert_eq!(lit.value_text, "1"); // Grammar parses number and unit separately
                             assert_eq!(lit.unit, "kOhm");
                        }
                        _ => panic!("Expected PhysicalLiteral for R1 parameter 'value'")
                    }
                }
                _ => panic!("Expected Named parameters for R1"),
            }

            let comp_c1 = &components_block.instantiations[1];
            assert_eq!(comp_c1.instance_name.name, "C1");
            assert_eq!(comp_c1.component_type.name, "Capacitor");
            assert!(comp_c1.parameters.is_some());
             match comp_c1.parameters.as_ref().unwrap() {
                 ComponentParameters::Positional(params) => {
                     assert_eq!(params.len(), 2);
                     match &params[0] {
                        Expression::PhysicalLiteral(lit) => {
                            assert_eq!(lit.value_text, "10");
                            assert_eq!(lit.unit, "uF");
                        }
                        _ => panic!("Expected PhysicalLiteral for C1 first positional parameter")
                     }
                     match &params[1] {
                        Expression::PhysicalLiteral(lit) => {
                             assert_eq!(lit.value_text, "16");
                             assert_eq!(lit.unit, "Vdc");
                         }
                         _ => panic!("Expected PhysicalLiteral for C1 second positional parameter")
                     }
                 }
                 _ => panic!("Expected Positional parameters for C1"),
             }

            // --- Check Connections Block ---
            let connections_block = board.body.iter().find_map(|item| match item {
                BoardItem::ConnectionsBlock(cb) => Some(cb),
                _ => None,
            }).expect("Connections block not found");
            assert_eq!(connections_block.connections.len(), 4);

            let conn1 = &connections_block.connections[0];
            match &conn1.source {
                ConnectionEndpoint::Identifier(id) => assert_eq!(id.name, "CLK"),
                _ => panic!("Expected Identifier source for conn1"),
            }
            match &conn1.target {
                ConnectionEndpoint::MemberAccess(ma) => {
                    match &ma.object {
                        Expression::Identifier(id) => assert_eq!(id.name, "R1"),
                        _ => panic!("Expected Identifier object for conn1 target"),
                    }
                    assert_eq!(ma.property.name, "1");
                }
                _ => panic!("Expected MemberAccess target for conn1"),
            }

            let conn4 = &connections_block.connections[3];
            match &conn4.source {
                ConnectionEndpoint::Identifier(id) => assert_eq!(id.name, "NetA"),
                _ => panic!("Expected Identifier source for conn4"),
            }
             match &conn4.target {
                 ConnectionEndpoint::MemberAccess(ma) => {
                     match &ma.object {
                         Expression::Identifier(id) => assert_eq!(id.name, "R1"),
                         _ => panic!("Expected Identifier object for conn4 target"),
                     }
                     assert_eq!(ma.property.name, "p2");
                 }
                 _ => panic!("Expected MemberAccess target for conn4"),
             }

        } else {
            panic!("Expected BoardDefinition as first item");
        }

        println!("Parser test completed successfully.");
    }
}