//! PDF binder — the sheet tree bound as a print-ready multipage document.
//!
//! Same sheets, second binding (docs/spec/Schematic_V4.md): the interactive
//! binding is SVG files with native hyperlinks; this one is a single
//! self-contained HTML file, one sheet per page, with an index page, a
//! title block on every sheet, and the inter-sheet links rewritten to
//! internal anchors so they survive print-to-PDF. The browser's print
//! engine is the PDF renderer — no new rendering stack, and the output is
//! byte-for-byte the same sheet geometry the SVG binding shows.

use super::svg::SheetOut;

/// Bind rendered sheets into one print-ready HTML document. `href_map`
/// maps each child sheet's SVG filename (as emitted into block hrefs) to
/// its slug, so links become internal `#sheet-<slug>` anchors.
pub fn bind_sheets(
    board: &str,
    sheets: &[SheetOut],
    href_map: &[(String, String)], // (svg filename, slug)
    tool_version: &str,
) -> String {
    let n = sheets.len();
    let mut html = String::new();
    html.push_str(&format!(
        r#"<!doctype html>
<meta charset="utf-8">
<title>{board} — schematic</title>
<style>
@page {{ size: A4 landscape; margin: 8mm; }}
* {{ box-sizing: border-box; }}
body {{ font-family: -apple-system, "Helvetica Neue", Arial, sans-serif; margin: 0; color: #222; }}
/* A4 landscape page box: 297×210mm − 2×8mm margins = 281×194mm. The
   fixed height is what lets max-height resolve — a small sheet scaled
   to page WIDTH otherwise explodes past the page. */
.page {{ height: 192mm; page-break-after: always; padding: 4mm; display: flex; flex-direction: column; border: 1.2px solid #444; margin-bottom: 6mm; overflow: hidden; }}
.page:last-child {{ page-break-after: auto; }}
.sheetwrap {{ flex: 1; min-height: 0; display: flex; align-items: flex-start; justify-content: center; overflow: hidden; }}
.sheetwrap svg {{ max-width: 100%; max-height: 100%; width: auto; height: auto; }}
@media print {{ .page {{ margin-bottom: 0; }} }}
.tblock {{ border-collapse: collapse; margin-left: auto; font-size: 10px; }}
.tblock td {{ border: 1px solid #444; padding: 2px 10px; }}
.tblock .b {{ font-weight: 700; }}
h1 {{ font-size: 20px; margin: 8px 0 2px; }}
.sub {{ color: #666; font-size: 12px; margin-bottom: 14px; }}
table.index {{ border-collapse: collapse; font-size: 13px; }}
table.index th, table.index td {{ border: 1px solid #999; padding: 5px 14px; text-align: left; }}
table.index th {{ background: #eef2fa; }}
a {{ color: #06c; text-decoration: none; }}
</style>
"#
    ));

    // ── Index page ──
    html.push_str("<section class=\"page\">\n");
    html.push_str(&format!("<h1>{board}</h1>\n"));
    html.push_str(&format!(
        "<div class=\"sub\">schematic — {n} sheet{} · generated by bhdl v{tool_version}</div>\n",
        if n == 1 { "" } else { "s" }
    ));
    html.push_str("<table class=\"index\"><tr><th>Page</th><th>Sheet</th><th>Gates</th></tr>\n");
    for (i, s) in sheets.iter().enumerate() {
        let anchor = if s.slug.is_empty() { "sheet-top".to_string() } else { format!("sheet-{}", s.slug) };
        html.push_str(&format!(
            "<tr><td>{}</td><td><a href=\"#{anchor}\">{}</a></td><td>{} unidiomized, {} collisions</td></tr>\n",
            i + 2,
            esc(&s.title),
            s.unidiomized,
            s.collisions,
        ));
    }
    html.push_str("</table>\n");
    title_block(&mut html, board, "index", 1, n + 1, tool_version);
    html.push_str("</section>\n");

    // ── Sheet pages ──
    for (i, s) in sheets.iter().enumerate() {
        let anchor = if s.slug.is_empty() { "sheet-top".to_string() } else { format!("sheet-{}", s.slug) };
        html.push_str(&format!("<section class=\"page\" id=\"{anchor}\">\n"));
        // Inline the SVG with block links rewritten to internal anchors —
        // print-to-PDF preserves internal links, so the drill-down works
        // in the bound document too.
        let mut svg = s.svg.clone();
        for (file, slug) in href_map {
            svg = svg.replace(
                &format!("href=\"{file}\""),
                &format!("href=\"#sheet-{slug}\""),
            );
        }
        html.push_str("<div class=\"sheetwrap\">");
        html.push_str(&svg);
        html.push_str("</div>\n");
        title_block(&mut html, board, &s.title, i + 2, n + 1, tool_version);
        html.push_str("</section>\n");
    }
    html
}

fn title_block(html: &mut String, board: &str, sheet: &str, page: usize, of: usize, version: &str) {
    html.push_str(&format!(
        "<table class=\"tblock\"><tr><td class=\"b\">{}</td><td>{}</td><td>sheet {page} / {of}</td><td>bhdl v{version}</td></tr></table>\n",
        esc(board),
        esc(sheet),
    ));
}

fn esc(s: &str) -> String {
    s.replace('&', "&amp;").replace('<', "&lt;")
}
